- build.sbt
- ops/src/main/scala/ammonite/ops/FileOps.scala
Would you be ok to be compatible with Java 7? Some people (me included) still have some machines around with it. The changes required are minor.
> Java 7 compatibility

- build.sbt
> Update Scala version to 2.11.6

- repl/src/main/scala/ammonite/repl/interp/Pressy.scala
Fix is in the first commit, the other one contains cleanups.
> Fix race condition

- repl/src/main/scala/ammonite/repl/interp/Preprocessor.scala
- repl/src/test/scala/ammonite/repl/FailureTests.scala
This solves #55. All REPL tests are passing. Should I write some tests or benchmarks?
> Lifting expressions to anonymous function application

- build.sbt
Hi Haoyi,
Scala 2.11.7 fixes some annoying bugs and has improved sorting performance. It would be great if you could release a new version of Ammonite built against it :D
> Add and use Scala 2.11.7

- repl/src/main/scala/ammonite/repl/Repl.scala
This commit does a few things:
* Shorten the "loading" message
* Include Ammonite version in banner
* Include Scala and Java versions in banner too
> Improve the REPL's startup banner.

- terminal/src/main/scala/ammonite/terminal/BasicFilters.scala
- terminal/src/main/scala/ammonite/terminal/TermCore.scala
This should work the same as bash et al.
If there is an "in progress" line it is preserved and redrawn
at position (0, 0).
> Support clearing the screen via C-l.

- .travis.yml
- repl/src/main/scala/ammonite/repl/interp/Classpath.scala
- repl/src/test/scala/ammonite/repl/AutocompleteTests.scala
If my understanding of https://github.com/lihaoyi/Ammonite/issues/148 is correct, this should fail the build until https://github.com/lihaoyi/Ammonite/pull/161 lands
> add openjdk to CI

- terminal/src/main/scala/ammonite/terminal/ReadlineFilters.scala
- terminal/src/main/scala/ammonite/terminal/SpecialKeys.scala
Yes, I'm one of those people who sometime use HOME/END and expect them to work :)
> terminal: support HOME and END keys

- terminal/src/main/scala/ammonite/terminal/ReadlineFilters.scala
- terminal/src/test/scala/ammonite/terminal/EditTests.scala
Does not modify the yank ring.
Tests pass fine. Please let me know if more tests are required.
> Use Ctrl-h for backspace

- repl/src/main/scala/ammonite/repl/interp/Interpreter.scala
- repl/src/test/resource/scripts/NestedScripts.scala
- repl/src/test/scala/ammonite/repl/ScriptTests.scala
> Fix loading scripts from other scripts

- ops/src/main/scala/ammonite/ops/FileOps.scala
- ops/src/main/scala/ammonite/ops/Path.scala
- ops/src/test/scala/test/ammonite/ops/ExampleTests.scala
- ops/src/test/scala/test/ammonite/ops/PathTests.scala
- repl/src/main/scala/ammonite/repl/IvyThing.scala
- repl/src/main/scala/ammonite/repl/Storage.scala
- repl/src/test/scala/ammonite/repl/session/AdvancedTests.scala
- repl/src/test/scala/ammonite/repl/session/FailureTests.scala
- Remove redundant tests
@Blaisorblade what do you think? It matches the behavior of http://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#startsWith(java.nio.file.Path) now
> - Remove ordered path operators for reals, replace with `startsWith`

- ops/src/main/scala/ammonite/ops/Shellout.scala
- ops/src/test/scala/test/ammonite/ops/ShelloutTests.scala
- readme/Ops.scalatex
Shellable now takes Seq[String] to allow for programmatically building up command-line args
> fix for #220

- repl/src/main/scala/ammonite/repl/interp/Interpreter.scala
- repl/src/test/resource/scripts/SheBang.scala
- repl/src/test/scala/ammonite/repl/ScriptTests.scala
- cut first line except linefeed to have no impact for counting line numbers.
> Script file should ignore Shebang

- repl/src/main/scala/ammonite/repl/interp/Classpath.scala
- repl/src/main/scala/ammonite/repl/interp/Compiler.scala
Also adds `ammonite.trace-classpath=true` property which enables more
verbose classpath logging.
> hopefully more robust classpath jar probing, fixes #168

- terminal/src/main/scala/ammonite/terminal/BasicFilters.scala
Fixes #223. No tests added. The test infrastructure seems to only run tests encoded into strings at the moment. So this test would be slightly more involved.
> Added support for exiting on end of file.

- repl/src/main/scala/ammonite/repl/interp/Pressy.scala
- repl/src/test/scala/ammonite/repl/AutocompleteTests.scala
* Adds Try to Pressy.scala to catch NPE thrown at Line 68.
* Adds test to AutocompleteTests
* The Failure case simply returns an empty Seq.
> Adds fix for #257

- repl/src/main/scala/ammonite/repl/interp/Pressy.scala
- repl/src/test/scala/ammonite/repl/AutocompleteTests.scala
Added a regression test against the fix for #252 to prevent it from resurfacing.
> Add regression test around #252 and fix formatting

- readme.md
- readme/Footer.scalatex
- readme/Index.scalatex
- readme/Repl.scalatex
- readme/Sample.scala
- readme/Shell.scalatex
- repl/src/main/scala/ammonite/repl/IvyThing.scala
- repl/src/main/scala/ammonite/repl/frontend/ReplAPI.scala
Paranoid sysadmins are paranoid.
> Fix as many http links as possible, to https.

- terminal/src/main/scala/ammonite/terminal/GUILikeFilters.scala
https://github.com/lihaoyi/Ammonite/issues/301
> #301 None.get on Shift+Tab without selection.

- repl/src/main/scala/ammonite/repl/interp/Compiler.scala
We use scct at Verizon and it doesn't seem to play nice with Ammonite.
> skip over the scct plugin since it doesn't work wtih ammonite

- .travis.yml
- build.sbt
@lihaoyi thanks for Ammonite, love it!
looking to get the conversation started for 2.11.8, and figure out what else should be done :)
> build with 2.11.8

- build.sbt
> Support for custom java options via JAVA_OPTS env var

- amm/interp/src/main/scala/ammonite/runtime/Interpreter.scala
- amm/runtime/src/main/scala/ammonite/runtime/tools/IvyThing.scala
- integration/src/test/resources/ammonite/integration/basic/ivyResolveSnapshot.sc
- integration/src/test/resources/some-dummy-library/build.sbt
- integration/src/test/resources/some-dummy-library/project/build.properties
- integration/src/test/scala/ammonite/integration/BasicTests.scala
- integration/src/test/scala/ammonite/integration/TestUtils.scala
See commit log for details. 
NOTE: I removed cache ivy resolvers because they don't seem to do anything.
Q: Should the docs be updated for this issue?
> fix for #433 - ivy pulls in changes to SNAPSHOT

- amm/src/main/scala/ammonite/Main.scala
Supporting multiple --predef-file options makes it easier to have a shared project-specific predef and a personal predef for a Scala project.
Note: I matched the existing behavior of `ammonite.runtime.Storage.Folder.loadPredef` to silently ignore file not found errors. I'm skeptical of that behavior, but it is preexisting so will match it.
> support multiple --predef-file options

- readme.md
- readme/Cookbook.scalatex
Fixes some typos in the cookbook doc and readme.
> Fix typos in documentation

- readme.md
because bookmarking http://www.lihaoyi.com/Ammonite/#Changelog didn't scroll to the right place in my browser and then i have to scroll up slightly. __I'M HAVING SERIOUS FIRST WORLD PROBLEMS HERE!!!__
> add maven central version badge to readme

- integration/src/test/scala/ammonite/integration/AmmoniteBridge.scala
- readme/Scripts.scalatex
This PR adds documentation detailing how to get classes from an SBT project onto the classpath of an ammonite script.
> Add sbt integration to docs

- readme/Footer.scalatex
I just want to indicate that this sentence is incomplete and offer a possible completion to the sentence :) You probably have something else in mind.
p.s. Still looking at Ammonite more :)
> Suggestion for hanging sentence

- sshd/src/main/scala/ammonite/sshd/util/Environment.scala
Previously, logging into an SSH session redirected `System.out` to the console. This caused problems with system behaviour, along with not being safe for multiple sessions.
While Scala's Console object only redirects `println` and not `System.out.println`, it is thread-local, and so behaves in a more sensible way when SSH sessions are active.
> Use Console for SSHD stream redirection

- readme/Sample.scala
I've tried to install ammonite on a few different machines using the instructions in the docs and often the `chmod` step gets rejected.
> Add sudo to chmod installation step

- amm/repl/src/main/scala/ammonite/repl/ReplAPI.scala
Modify the type check for Unit due to a bug in Scala's reflection when applied to certain class annotations in Hadoop jars. The type check would consistently throw an exception when applied to certain Hadoop classes annotated with `org.apache.hadoop.classification.InterfaceAudience`.
See https://issues.scala-lang.org/browse/SI-10129 for additional details.
Workaround: Check the value to be printed against Unit's known instances instead of using the typeOf check.
> work around scala reflection bug

- .travis.yml
- ci/build.sc
it's not finished yet.  but let's start a discussion.
> (WIP) Publishing for Scala 2.10 and 2.11

- readme/Shell.scalatex
Add `read` to docs when comparing with `cat`
> Add `read` to docs when comparing with `cat`

- readme/Repl.scalatex
#553 
never actually written latex before and had nothing set up in my editor to help me, so should probably look extra carefully at this :sweat_smile:
> alt sbt project integration to get around scala 2.12/2.11.11 issues

- amm/runtime/src/main/scala/ammonite/runtime/ClassLoaders.scala
Related to https://gitter.im/lihaoyi/Ammonite?at=5919a7c400efc2bb3e6c520d
> Fix to prevent mtiming non-existent Paths

- amm/runtime/src/main/scala/ammonite/runtime/ImportHook.scala
- amm/runtime/src/main/scala/ammonite/runtime/tools/IvyThing.scala
- amm/src/test/scala/ammonite/session/ImportHookTests.scala
I've never worked with Ammonite source before, but here is an attempt to allow cross-versioning.  Please comment if you believe more test cases are needed or if you believe there are better ways to handle the issue.
> #635 Allow full cross-versioning

- integration/src/test/resources/ammonite/integration/basic/PlayFramework.sc
- readme/Cookbook.scalatex
Hi, I thought Ammonite was great for ad hoc database work and might be worth including in the cookbook section.
What do you think ?
> Add Cookbook example for sql database

- build.sbt
[for somewhat selfish reasons :sweat_smile:](https://github.com/coursier/coursier/issues/602)
> update to coursier RC8

- readme/Repl.scalatex
As far as I can tell, a dollar was intended here.
> add missing dollar sign in exec import

- readme/Ops.scalatex
Fix for https://github.com/lihaoyi/Ammonite/issues/688
> Fix #688 Clarify % operator documentation for non-zero return-code

- amm/src/main/scala/ammonite/main/ProxyFromEnv.scala
Added hyphen to character classes in the UrlPattern.
Closes #707
> Added hyphens to UrlPattern

- build.sbt
- project/plugins.sbt
Latest stable release or coursier
> Update coursier to 1.0.0

- terminal/src/main/scala/ammonite/terminal/Utils.scala
@lihaoyi this one should be ready to review. Basic sh is enough for the job.
I'll try to get rid of tput in separate PR as it needs more debugging.
> Remove bash terminal dependencies

- build.sbt
- build.sc
This should fix https://github.com/lihaoyi/mill/issues/139
> Upgrade jline to 2.14.5

- readme/Repl.scalatex
idk if anybody else has encountered this with projects still on sbt 0.13?
could just be my local config and/or that project setup/plugins is/are borked
either way, feel free to add this to evidence in the "sbt is hard, try mill" case :)
[potentially related](https://github.com/sbt/sbt/issues/3006#issuecomment-355199121)
> scala 2.10 compat in repl readme

- amm/runtime/src/main/scala/ammonite/runtime/Classpath.scala
Avoid exporting Java 9 rt.jar if one is already in the classpath in order to mainly save time (exporting rt.jar can take seconds).
One use case is mill's client/server where [the client exports rt.jar once and caches it which it then provides the cached rt.jar to the mill's server](https://github.com/lihaoyi/mill/blob/712f331d24d0934cd9c653a12be7e47e1fff1f5d/clientserver/src/mill/clientserver/Client.java#L33-L37) (that uses Ammonite).
The detection of rt.jar is similar to [mill's](https://github.com/lihaoyi/mill/blob/712f331d24d0934cd9c653a12be7e47e1fff1f5d/core/src/mill/util/ClassLoader.scala#L11-L17).
> Optimize away Java 9 rt.jar export if one is already in the classpath

- amm/repl/src/main/scala/ammonite/repl/FrontEndUtils.scala
> Fix FrontEndUtils width and height on Windows

- readme/Scripts.scalatex
And an example for usage in an sbt project.
> Fixes '--predef does not work anymore'

- amm/repl/src/main/scala/ammonite/repl/tools/source.scala
- amm/repl/src/test/scala/ammonite/session/FailureTests.scala
- amm/src/main/scala/ammonite/main/Router.scala
- amm/util/src/main/scala/ammonite/util/Model.scala
- amm/util/src/main/scala/ammonite/util/Res.scala
- ops/src/test/scala/test/ammonite/ops/ExampleTests.scala
This pull request fixes several minor typos detected by [misspell](https://github.com/client9/misspell).
> Fix minor typos

- .travis.yml
- amm/repl/src/test/scala/ammonite/TestRepl.scala
- amm/repl/src/test/scala/ammonite/session/EvaluatorTests.scala
- amm/runtime/src/main/scala/ammonite/runtime/tools/IvyThing.scala
- appveyor.yml
- build.sc
Fixes https://github.com/lihaoyi/Ammonite/issues/870.
> Switch to scala 2.12.7

- .travis.yml
- amm/repl/src/main/scala-2.12/ammonite/repl/tools/HighlightJava.scala
- amm/repl/src/test/scala/ammonite/TestRepl.scala
- amm/repl/src/test/scala/ammonite/unit/ParserTests.scala
- amm/repl/src/test/scala/ammonite/unit/SourceTests.scala
- amm/src/main/scala/ammonite/main/Cli.scala
- amm/src/main/scala/ammonite/main/Scripts.scala
- amm/src/test/scala/ammonite/main/MainTests.scala
- integration/src/test/resources/ammonite/integration/basic/SourceDownload.sc
- integration/src/test/scala/ammonite/integration/BasicTests.scala
- ops/src/main/scala/ammonite/ops/Shellout.scala
- readme/Sample.scala
- terminal/src/test/scala/ammonite/terminal/Checker.scala
Just replace the JDK 9 stuff with JDK 11, keep JDK 8.
> Switch to JDK 11

- amm/repl/src/main/scala/ammonite/repl/Repl.scala
- amm/repl/src/main/scala/ammonite/repl/ReplAPI.scala
- amm/repl/src/test/scala/ammonite/TestRepl.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
That also makes it accessible when using Ammonite as a library, which is what actually interests me here…
> Make the presentation compiler accessible from the REPL API

- amm/interp/src/main/scala-2.12/scala/tools/nsc/CustomZipAndJarFileLookupFactory.scala
https://travis-ci.org/lihaoyi/Ammonite/jobs/471031887#L1969
> Fix build for early 2.12 versions

- amm/interp/src/main/scala-2.12/scala/tools/nsc/CustomZipAndJarFileLookupFactory.scala
See https://github.com/lihaoyi/Ammonite/pull/911.
> Fix early 2.12 versions stuff in release stages

- amm/runtime/src/main/scala/ammonite/runtime/Classpath.scala
Fixes https://github.com/lihaoyi/Ammonite/issues/797.
> Fix canBeOpenedAsJar check

- readme/Ops.scalatex
... and github editor added newline at end.
> typo in readme/Ops.scalatex

- readme/Shell.scalatex
* add a short paragraph about installation via FreeBSD pkg / port
> Add hint for installing under FreeBSD

- amm/interp/src/main/scala/ammonite/interp/InterpAPI.scala
- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/repl/src/main/scala/ammonite/main/Defaults.scala
- amm/repl/src/test/scala/ammonite/session/ProjectTests.scala
- amm/runtime/src/main/scala/ammonite/runtime/ImportHook.scala
- amm/runtime/src/main/scala/ammonite/runtime/Storage.scala
- amm/runtime/src/main/scala/ammonite/runtime/tools/IvyThing.scala
- amm/src/test/resources/scripts/loadIvyAdvanced.sc
- build.sc
~(Waiting for it to be released and sync-ed to Maven Central.)~
> Switch to coursier 1.1.0-M13-1

- amm/repl/src/test/scala/ammonite/session/EvaluatorTests.scala
- amm/runtime/src/main/scala/ammonite/runtime/Evaluator.scala
Fixes https://github.com/lihaoyi/Ammonite/issues/938.
> Fix issue when importing from val with class wrapping

- amm/repl/src/main/scala/ammonite/repl/tools/SourceRuntime.scala
the source not worked in Both Mac and Linux, because running less using PIPE instead of Inherit
> Fix bug for builtin "source"

- readme/Repl.scalatex
- readme/Scripts.scalatex
Fixes #1003 by updating readme to reflect changes from #990
> Update readmes to reference coursierapi

- .travis.yml
- amm/interp/src/main/scala/ammonite/interp/internal/CustomURLZipArchive.scala
- amm/repl/src/test/scala/ammonite/TestUtils.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
- amm/repl/src/test/scala/ammonite/session/ImportHookTests.scala
- appveyor.yml
- build.sc
- readme/Footer.scalatex
Supersedes https://github.com/lihaoyi/Ammonite/pull/1041.
> Upgrade to Scala 2.12.11

- readme/Repl.scalatex
The code is comparing unrelated types.
> Fix minor detail on the Repl docs

- amm/interp/src/main/scala-2.13/ammonite/interp/CompilerCompatibility.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
Fixes https://github.com/lihaoyi/Ammonite/issues/1080.
> Ensure -Ymacro-annotations works fine

- amm/interp/src/main/scala/ammonite/interp/DependencyLoader.scala
- amm/interp/src/main/scala/ammonite/interp/script/AmmoniteBuildServer.scala
- amm/interp/src/main/scala/ammonite/interp/script/Diagnostic.scala
- amm/interp/src/main/scala/ammonite/interp/script/DummyBuildServerImplems.scala
- amm/interp/src/main/scala/ammonite/interp/script/PositionOffsetConversion.scala
- amm/interp/src/main/scala/ammonite/interp/script/Script.scala
- amm/interp/src/main/scala/ammonite/interp/script/ScriptCache.scala
- amm/interp/src/main/scala/ammonite/interp/script/ScriptCompileResult.scala
- amm/interp/src/main/scala/ammonite/interp/script/ScriptCompiler.scala
- amm/interp/src/main/scala/ammonite/interp/script/ScriptProcessor.scala
- amm/interp/src/main/scala/ammonite/interp/script/SingleScriptCompiler.scala
- amm/src/main/scala/ammonite/Main.scala
- amm/src/test/resources/bsp/import-file/lib.sc
- amm/src/test/resources/bsp/import-file/main.sc
- amm/src/test/resources/bsp/semdb/other.sc
- amm/src/test/scala/ammonite/interp/script/AmmoniteBuildServerTests.scala
- amm/src/test/scala/ammonite/interp/script/TestBuildClient.scala
Cache compilation results in memory, so that we don't spend time recompiling everything all the time, in particular.
> Tweak BSP support

- amm/interp/src/main/scala/ammonite/interp/script/SingleScriptCompiler.scala
- amm/src/test/scala/ammonite/interp/script/AmmoniteBuildServerTests.scala
The whole target directory used to be wiped upon (re)compilation. This could confuse file watchers of BSP clients, watching specific directories. We only remove the files from now on. Keeping empty directories shouldn't be a problem…
> Don't delete sub-directories from target directory in BSP

- .travis.yml
- amm/interp/src/main/scala/ammonite/interp/script/AmmoniteBuildServer.scala
- appveyor.yml
- build.sc
Includes https://github.com/lihaoyi/Ammonite/pull/1104.
> Add scala 2.12.12 support

- .github/workflows/actions.yml
- readme/Sample.scala
Just gonna skip the entire Ammonite-Shell stdout capturing, since it doesn't work properly and is a relatively low priority feature for now
> WIP Try to fix publishDocs github action

- .github/workflows/actions.yml
- .github/workflows/publishDocs.yml
- .github/workflows/publishExecutable.yml
- .github/workflows/release1.yml
- .github/workflows/release2.yml
- .github/workflows/release3.yml
This largely enhances readability in GitHub UI.
> CI: Use better workflow names

- build.sbt
- build.sc
- ci/upload.sc
This should fix the release process.
I think a review is essential here. The CI will not help much until we merge into master and see a release happen.
> Fix github urls for upload and pom metadata

- amm/repl/api/src/main/scala/ammonite/repl/FullReplAPI.scala
Old url does not work anymore. (changed in browser)
> fix ammonite url in hepl message

- .github/workflows/publishDocs.yml
- amm/repl/api/src/main/scala/ammonite/repl/FullReplAPI.scala
- build.sbt
- ops/src/test/scala/test/ammonite/ops/ExampleTests.scala
- readme/ANSI.scala
- readme/Footer.scalatex
- readme/Ops.scalatex
- readme/Sample.scala
Umm.. was failing with `sh: 1: cannot open /dev/tty: No such device or address`.   
GH Actions probably doesn't have a tty/console when runs these, obviously... 😄 
I found this hack: https://github.com/actions/runner/issues/241#issuecomment-745902718
> Fix compare in docs

- readme/Index.scalatex
Updated 'find the follow book' to 'find the following book'
> Fixed a typo

- amm-template.sh
- build.sc
Fix the issue https://github.com/com-lihaoyi/Ammonite/issues/1018
> Fix scala version in bootstrap script

- build.sc
(Follow up of https://github.com/com-lihaoyi/Ammonite/pull/1201)
> Increase release timeouts to 10 minutes

- readme/Footer.scalatex
Hey, last year I gave a talk about why bash is a bad solution and how to replace it with Ammonite. As there is already a section with the talks I thought we may want to have it there as well. And its quite recent, so in some way it shows that project is alive enough for people to talk about it.
> Add a talk from scalawave 2018

- .github/workflows/actions.yml
- build.sc
Probably needs https://github.com/scalameta/scalameta/pull/2502.
> Update Scala to 2.13.7

- amm/src/main/scala/ammonite/Main.scala
- amm/src/main/scala/ammonite/main/Config.scala
- amm/src/test/scala/ammonite/main/InProcessMainMethodRunnerRawArgs.scala
- amm/src/test/scala/ammonite/main/MainTests.scala
Fix for #1031. Hopefully the tests are alright.
> Added version flag option

- amm/src/main/scala/ammonite/MainRunner.scala
Now a user can do two things during `--watch`: either `Ctrl-C` to exit, or `Enter` to re-run. This is the first step in supporting the same functionality in Mill https://github.com/com-lihaoyi/mill/issues/490.
I also incorporated some of the upstream improvements in the Mill implementation of `def watchAndWait` https://github.com/com-lihaoyi/mill/blob/8c2ee3801f6471d4bf526f638c3668e4337c0fa6/main/src/mill/main/MainRunner.scala#L51-L67, which we should be able to largely replace with the original except for an override wrapping the original in the two `setIdle` calls.
The nested functions were getting messy, so moved some of them out into separate helpers
Tested manually by running `./mill -i amm[2.12.10].run -w foo.sc x 1 true` on a dummy script, verified that pressing `Enter` causes it …
> Allow users to re-run watched scripts by pressing enter

- .github/workflows/actions.yml
- build.sc
Fixes https://github.com/com-lihaoyi/Ammonite/issues/1293
> Update Scala to 2.13.9

- .github/workflows/actions.yml
- build.sc
> Update Scala to 2.13.10

- amm/repl/src/test/scala/ammonite/session/ProjectTests.scala
Seems https://repo.typesafe.com/typesafe/ivy-releases is experiencing issues right now…
> Fix resolver test

- .github/workflows/actions.yml
- build.sc
> Support Scala 2.13.11 and 2.12.18

- amm/src/main/scala/ammonite/AmmoniteMain.scala
Just stumbled upon that while working on https://github.com/com-lihaoyi/Ammonite/pull/1369…
> Clean-up some unused imports

- amm/interp/src/main/scala/ammonite/interp/script/AmmoniteBuildServer.scala
- amm/interp/src/main/scala/ammonite/interp/script/DummyBuildServerImplems.scala
- build.sc
Backports of #1358 and #1368 into 2.x branch (cherry-picked and solved a conflict)
> Backport Updates to 2.x

- .scalafmt.conf
This is is copied straight from Mill.
> Add a .scalafmt.conf

- .github/workflows/release.yml
- build.sc
This hopefully let the publishing process fail less often.
> CI: Increase shard count in release process

- build.sc
This completes https://github.com/com-lihaoyi/Ammonite/pull/1453
> Add ttl param to checkPublishedArtifact (commit got lost in previous commit)

- build.sc
Fix https://github.com/com-lihaoyi/Ammonite/issues/1491
> Correct version mangling in release tooling (use `DEFAULT_SCALA_VERSION`)

- .github/workflows/run-tests.yml
- build.sc
Supersedes https://github.com/com-lihaoyi/Ammonite/pull/1534 & https://github.com/com-lihaoyi/Ammonite/pull/1532
Closes https://github.com/com-lihaoyi/Ammonite/issues/1533
> Add support for  Scala 3.4.3

- .github/workflows/run-tests.yml
- amm/repl/src/test/scala/ammonite/DualTestRepl.scala
- amm/repl/src/test/scala/ammonite/session/BuiltinTests.scala
- build.sc
Closes https://github.com/com-lihaoyi/Ammonite/issues/1557
> Bump Scala to 3.5.1
