- .travis.yml
- build.sbt
- ops/src/main/scala/ammonite/ops/Shellout.scala
- pprint/src/main/scala/ammonite/pprint/PPrint.scala
- repl/src/main/scala-2.10/ammonite/repl/interp/CompilerCompatibility.scala
- repl/src/main/scala-2.11/ammonite/repl/interp/CompilerCompatibility.scala
- repl/src/main/scala/ammonite/repl/IvyThing.scala
- repl/src/main/scala/ammonite/repl/interp/Compiler.scala
- repl/src/main/scala/ammonite/repl/interp/Evaluator.scala
- repl/src/main/scala/ammonite/repl/interp/Pressy.scala
- tools/src/main/scala/ammonite/tools/Tools.scala
This PR adds support for Scala 2.10, if it's something you'd like to have in Ammonite.
Don't merge now !!!
Some tests don't pass, for various reasons (some Ivy dependencies not available in 2.10, ...), but I would see clearer in them if they all would pass in 2.11 :P
Basic repl interaction is ok though (results display, autocompletion, Ivy deps, ...)
> Early Scala 2.10 support

- repl/src/main/scala/ammonite/repl/IvyThing.scala
This almost shuts Ivy, except in case of error.
It can be made more verbose again by increasing `maxLevel` here:
https://github.com/lihaoyi/Ammonite/commit/fe609776aa4dd33df161dbb09457a7fce3e2cb5b#diff-0c45674fa431da1de377ef0cd36e5af7R35
but at `maxLevel = 2`, it's actually quite similar to what it currently is. There seems to be no middle ground (except by manually filtering the most annoying messages :-)
Fixes https://github.com/lihaoyi/Ammonite/issues/54
> Less verbose Ivy

- pprint/src/main/scala/ammonite/pprint/Core.scala
- pprint/src/main/scala/ammonite/pprint/PPrint.scala
- pprint/src/test/scala/ammonite/pprint/PPrintTests.scala
- repl/src/main/scala/ammonite/repl/Repl.scala
- repl/src/test/scala/ammonite/repl/EulerTests.scala
This will fix issue #48. PPrinters created with PPrinter.apply are now truncating thier outputs. Values wrapped in the type Full[T] will print normally with all output.
> Truncating long PPrint output

- repl/src/main/scala/ammonite/repl/Util.scala
SyntaxError.msg throws an `IndexOutOfBoundsException` if the failing position is at the end of the last line.
> Bugfix in SyntaxError

- repl/src/main/scala/ammonite/repl/IvyThing.scala
- repl/src/main/scala/ammonite/repl/Util.scala
- repl/src/main/scala/ammonite/repl/frontend/ReplAPI.scala
- repl/src/main/scala/ammonite/repl/interp/Interpreter.scala
- repl/src/main/scala/ammonite/repl/interp/Preprocessor.scala
- repl/src/test/resource/scripts/Annotation.scala
- repl/src/test/resource/scripts/CompilationError.scala
- repl/src/test/resource/scripts/LoadIvy.scala
- repl/src/test/resource/scripts/MultiBlockError.scala
- repl/src/test/resource/scripts/PreserveImports.scala
- repl/src/test/resource/scripts/SyntaxError.scala
- repl/src/test/scala/ammonite/repl/ScriptTests.scala
Scripts can be loaded with `load.script`. It support breaking scripts up to multiple compilation blocks with the separator `@\n`. The printing snippets generated by `Preprocessor` are discarded in scripts. Errors in script compilation are reported with `Interpreter.stdout`.
> Script loading support

- build.sbt
- repl/src/main/scala/ammonite/repl/Repl.scala
- repl/src/main/scala/ammonite/repl/Storage.scala
- repl/src/main/scala/ammonite/repl/Util.scala
- repl/src/main/scala/ammonite/repl/frontend/ReplAPI.scala
- repl/src/main/scala/ammonite/repl/interp/Interpreter.scala
- repl/src/test/resource/scripts/BlockSepSyntax.scala
- repl/src/test/scala/ammonite/repl/Checker.scala
- repl/src/test/scala/ammonite/repl/ScriptTests.scala
- repl/src/test/scala/ammonite/repl/UnitTests.scala
This addresses issues #99 and #101. A new class `History` and a new singleton `Storage` is added. `History` has a `PPrinter` that prints it in script syntax. Script syntax was modified, so now not just `@\n` but anything matching the regex `@[\n ]+` is accepted as compilation block separator. `History` also has a `last(lines: Int)` method. `Storage` stores history in the `~/.ammonite/history` file with YAML syntax.
> History YAML storage and pretty printing

- repl/src/main/scala/ammonite/repl/Repl.scala
- repl/src/main/scala/ammonite/repl/Storage.scala
- repl/src/main/scala/ammonite/repl/frontend/FrontEnd.scala
- repl/src/main/scala/ammonite/repl/interp/Interpreter.scala
- terminal/src/main/scala/ammonite/terminal/Term.scala
- terminal/src/main/scala/ammonite/terminal/TermCore.scala
- Predef script is now loaded from `.ammonite/predef.scala`
- `ammonite-terminal` now properly strips ansi colors from prompt when calculating width
- Move `consoleDim` from `ammonite.repl.Repl` into `ammonite.terminal.Term`, and make `Repl` access it through `ammonite.repl.frontend.FrontEnd.Ammonite` to keep `Repl` free of too much bash/unix-isms
- predef script now uses multi-unit script format
> Misc Fixes

- repl/src/test/scala/ammonite/repl/Checker.scala
- repl/src/test/scala/ammonite/repl/FailureTests.scala
- repl/src/test/scala/ammonite/repl/ScriptTests.scala
This PR makes `Checker` in REPL test hadnle the expected output as a vim nomagic mode regex. This way we can handle more possible right outputs with ease. Regex special characters in expected output are handled as literals unless they are prefixed with `\`. Literal `\` itself needs to be escaped.
> Checker regex

- repl/src/main/scala/ammonite/repl/interp/Evaluator.scala
- repl/src/main/scala/ammonite/repl/interp/Interpreter.scala
- repl/src/test/scala/ammonite/repl/AdvancedTests.scala
- repl/src/test/scala/ammonite/repl/AutocompleteTests.scala
- repl/src/test/scala/ammonite/repl/EvaluatorTests.scala
- repl/src/test/scala/ammonite/repl/ProjectTests.scala
- repl/src/test/scala/ammonite/repl/ScriptTests.scala
- Don't cache manually-entered commands; it makes the mangled names of classes really ugly =/
- Don't cache the `ReplBridge` instantiation; it turns out that this was what was causing that compiler error that @laci37 was seeing. There's probably a separate bug here, but we can remove this instantiation when we fix that bug. Apart from happening on 2.10, the same compiler error was happening intermittently in 2.11 too
- Re-enable all the tests we disabled in 2.10
- Move the last few manual calls to `scala.util.Properties` onto `scala2_10`
> Fix compiler error on parsing

- build.sbt
- ops/src/main/scala/ammonite/ops/FileOps.scala
- ops/src/main/scala/ammonite/ops/Model.scala
- repl/src/main/scala/ammonite/repl/Repl.scala
- repl/src/main/scala/ammonite/repl/Storage.scala
- repl/src/main/scala/ammonite/repl/Util.scala
- repl/src/main/scala/ammonite/repl/frontend/FrontEnd.scala
- repl/src/main/scala/ammonite/repl/frontend/ReplAPI.scala
- repl/src/main/scala/ammonite/repl/interp/Compiler.scala
- repl/src/main/scala/ammonite/repl/interp/Evaluator.scala
- repl/src/main/scala/ammonite/repl/interp/Interpreter.scala
- repl/src/main/scala/ammonite/repl/interp/Preprocessor.scala
- repl/src/test/scala/ammonite/repl/AdvancedTests.scala
- repl/src/test/scala/ammonite/repl/Checker.scala
- repl/src/test/scala/ammonite/repl/MemoryStorage.scala
- repl/src/test/scala/ammonite/repl/ProjectTests.scala
- repl/src/test/scala/ammonite/repl/ScriptTests.scala
- repl/src/test/scala/ammonite/repl/UnitTests.scala
- Make `stat` return `null` if it can't provide owner/group, rather than a lambda that blows up when called
- Dotfiles don't show up in LsSeq's pretty-printing
- Renamed `history` to `fullHistory`, added a session-local `history`
- Simplified `History` pretty-printing and storage
- Moved everything in `Storage` over to use `ammonite.ops`
- Replace `defaultImports` with `defaultPredef`
- Remove `ReplBridge` string-eval-initialization with classloader hackery to load multiple copies of the pre-compiled code
- `cd!` now throws if the target isn't a valid directory
- Replaced `pprintln` import with `show`, which by default does not truncate
Fixes #131 #132 #135 (at least partially). The ProjectTests don't pass yet but almost...
> Grab bag of fixes

- terminal/src/main/scala/ammonite/terminal/ReadlineFilters.scala
Ctrl-f was erroneously moving back intead of forward.
Alt-delete's behavior is identical to Ctrl-w, but was
missing.
> Fix Ctrl-f and add Alt-delete.

- terminal/src/main/scala/ammonite/terminal/BasicFilters.scala
Most tools only use C-d to exit when the line is empty. Previously
a C-d would exit instead of delete, which will be surprising for
bash users.
> Enable C-d to delete when line is not empty.

- terminal/src/main/scala/ammonite/terminal/ReadlineFilters.scala
This commit also makes some adjustments to the history code
that hopefully make it a bit clearer what is going on.
It also makes a change to cursor positioning. In most
readline-based programs (e.g. bash), if the cursor is
currently at the end of the line, it will remain at the
end of the line after moving through the history. The
current behavior leaves the cursor at position 0. With
this change, a specific check is made to see if the
cursor is at the end of line, and if so the cursor
is moved to the "new" end of the line.
> Add support for C-p/C-n for prev/next in history.

- repl/src/main/scala/ammonite/repl/interp/Classpath.scala
Otherwise, startup will fail for openjdk because the classpath includes
an entry like this:
/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/libatk-wrapper.so
and initializing the compiler symbol table will fail with this (silenced)
error message:
error while loading <root>, Error accessing /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/libatk-wrapper.so
> only add jar files as jar dependencies, fixes #148

- repl/src/main/scala-2.10/ammonite/repl/interp/CompilerCompatibility.scala
- repl/src/main/scala-2.11/ammonite/repl/interp/CompilerCompatibility.scala
- repl/src/main/scala/ammonite/repl/frontend/ReplAPI.scala
- repl/src/main/scala/ammonite/repl/interp/Compiler.scala
- repl/src/main/scala/ammonite/repl/interp/Evaluator.scala
- repl/src/main/scala/ammonite/repl/interp/Interpreter.scala
- repl/src/test/scala/ammonite/repl/AdvancedTests.scala
Fixes https://github.com/lihaoyi/Ammonite/issues/145
I haven't added tests for when loading a plugin fails. Having the ability to add resources to the class loader on the fly, to add a `scalac-plugin.xml`, would make that easier. One could directly write the plugin from Ammonite then.
> Load available compiler plugins

- .travis.yml
- build.sbt
It would be great if you could publish for Scala 2.10.5 because otherwise one can't upgrade to SBT 0.13.9 (which brings a lot of fixes and maybe some speedups).
Thanks!
> Add Scala 2.10.5 for SBT 0.13.9

- project/Constants.scala
Once `0.4.5` is released, version should become `0.4.6-SNAPSHOT` (`.6`, not `.5`), or `0.5.0-SNAPSHOT`, ...
> Fix version

- terminal/src/main/scala/ammonite/terminal/Utils.scala
This PR simply reenables the code disabling Ctrl-y, while ensuring it does no harm where Ctrl-y is unsupported (Linux). After this commit, Ctrl-y works as expected in Emacs/bash/readline: it yanks/pastes text killed/cut with Ctrl-k and similar combos.
Fixes #180.
> Disable Ctrl-y wherever possible (fix #180)

- repl/src/main/scala/ammonite/repl/frontend/AmmoniteFrontEnd.scala
Previous version was just looking for CR.  This meant when pasting a multiline block without {} from Vim, an error would be thrown.  Now we will look for both CR and newline.
> Fix for multiline blocks separated by line breaks 

- readme.md
Updated documentation link from lihaoyi.github.io/Ammonite to
http://lihaoyi.github.io/Ammonite.
When lihaoyi.github.io/Ammonite is used as the link to the
documentation it resolves to: https://github.com/lihaoyi/Ammonite/blob/master/lihaoyi.github.io/Ammonite because it is a relative url.
> Fix documentation url

- repl/src/main/scala/ammonite/repl/interp/Pressy.scala
Added a Try around the awaitResponse method to prevent an Exception
killing the Ammonite Repl. The awaitResponse method throws an Exception
if a match can't be found for a completion.
The Failure case simply returns an empty List[pressy.Member]. This seems
like the simplest and least invasive fix for issue #252, although it may
not be ideal.
> Fix Tab completion on Array causes ammonite to exit (#252)

- integration/src/test/scala/ammonite/integration/StandaloneTests.scala
- shell/src/main/resources/ammonite/shell/empty-predef.scala
I've updated the exec method to use an empty predef file, thus
isolating the tests from the effects of a user-supplied predef file.
It used to be that any output from a user's predef.scala file would
conflict with the 'hello test causing it to fail.
issue: #262
> Fix StandaloneTests.hello failure with predef.scala #262

- build.sbt
- readme/Repl.scalatex
- repl/src/main/scala/ammonite/repl/IvyThing.scala
- repl/src/main/scala/ammonite/repl/frontend/ReplAPI.scala
- repl/src/main/scala/ammonite/repl/interp/Interpreter.scala
- repl/src/test/scala/ammonite/repl/session/ProjectTests.scala
I don't know if this is what you had in mind but this works ok for me. Feel free to change, adjust, etc...
When I ran the repl tests, I had contradictory messages like:
```
[info] Tests: 166
[info] Passed: 166
[info] Failed: 0
[error] (ops/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 632 s, completed 10/12/2015 10:16:55 PM
```
Maybe you can help me there?
> Added the possibility to specify resolvers from the repl

- repl/src/main/scala/ammonite/repl/interp/Pressy.scala
- repl/src/test/scala/ammonite/repl/AutocompleteTests.scala
When trying to autocomplete an unknown or mistyped import such as:
```
import scala.collction.<tab>
```
Ammonite exits with the following error:
```
@ import scala.collction.Exception in thread "main"
java.lang.ClassCastException: scala.reflect.internal.Trees$Select
cannot be cast to scala.reflect.internal.Trees$Ident
at ammonite.repl.interp.Pressy$Run.prefixed(Pressy.scala:135)
at ammonite.repl.interp.Pressy$$anon$3.complete(Pressy.scala:231)
```
The error is due to casting a scala.reflect.internal.Trees$Select to a
scala.reflect.internal.Trees$Ident. The fix simply tests for the
Trees$Ident type before casting to it.
If the expr type of the Import is not a Trees$Ident then we return no
matches.
Also added a couple of tests for the fix to repl/AutocompleteTests.
> fix crash when autocompleting an unknown import

- .travis.yml
- build.sbt
- project/Constants.scala
- repl/src/main/scala-2.11/ammonite/repl/frontend/TPrintImpl.scala
- repl/src/main/scala/ammonite/repl/Storage.scala
- repl/src/main/scala/ammonite/repl/frontend/AmmoniteFrontEnd.scala
- repl/src/main/scala/ammonite/repl/frontend/FrontEnd.scala
- repl/src/test/scala-2.11/ammonite/terminal/TPrintTests.scala
- repl/src/test/scala/ammonite/repl/session/ProjectTests.scala
- terminal/src/main/scala/ammonite/terminal/GUILikeFilters.scala
- terminal/src/main/scala/ammonite/terminal/ReadlineFilters.scala
- terminal/src/main/scala/ammonite/terminal/TermCore.scala
- terminal/src/main/scala/ammonite/terminal/Utils.scala
- terminal/src/test/scala/ammonite/terminal/Checker.scala
- terminal/src/test/scala/ammonite/terminal/EditTests.scala
- terminal/src/test/scala/ammonite/terminal/HistoryTests.scala
- terminal/src/test/scala/ammonite/terminal/Main.scala
- terminal/src/test/scala/ammonite/terminal/NavigationTests.scala
Re-implementation of https://github.com/lihaoyi/Ammonite/pull/281, but better
- Searches contents, not just prefixes
- Underlines things which are being searched for, making it relatively clear (?) when a search is taking place and when it isn't
- Relatively intuitive (?) behavior around starting, ending, and navigating through the search history. In particular:
- It supports both `UP` and `Ctrl-R` as ways to start a search
- Printable characters or backspaces modify the search in place, and narrow it in the case of additional characters.
- Any control character ends the search and forwards to the default behavior; e.g. `ENTER` ends the search and executes the command, `LEFT`/`RIGHT` end the search and move the cursor, etc.
- Only uses two `var`s instead of seven
Misc changes 
- Upgrade …
> History search

- project/build.sbt
I found that the [ScalaDoc](http://www.lihaoyi.com/Ammonite/api/ops/index.html) does not link to Scala standard library and other dependencies. This patch fixes the problem.
> Configure external links in ScalaDoc

- repl/src/main/scala/ammonite/repl/interp/Compiler.scala
- repl/src/main/scala/ammonite/repl/interp/Interpreter.scala
- repl/src/main/scala/ammonite/repl/interp/Pressy.scala
- repl/src/test/scala/ammonite/repl/session/AdvancedTests.scala
It is currently not possible to have a predef that manipulates compiler settings, because the compiler that is used during initialization is replaced before the REPL is available to the user. This PR fixes that as follows:
- `initGlobalBits ` now takes a `Settings` to use, rather than constructing a new one.
- `Compiler` and `Pressy` now take a `Settings`, which is passed to `initGlobalBits`.
- `Interpreter` now constructs a new `Settings` for the initial compiler, and thereafter uses a *copy* of the settings from the previous compiler.
The provided unit test fails in `master` at the moment, but passes with these changes.
> preserve settings when replacing compilers

- repl/src/main/scala/ammonite/repl/IvyThing.scala
Addresses this bug: #300 
Problem is that locally published jars in Ivy have a different pattern than they do in the remote repo. Specifically the Ivy.xml file, which lists the jar dependencies, is in a different subdirectory from the Jar. Annoyingly Ivy fails silently on this and just assumes you have no dependencies, and copies your local jar to the ivy cache with a default ivy.xml :/
I don't really grok Ivy that well, but I wonder if some of the other ivy issues are related (such as #387) to this. Maybe other patterns should be updated to include [type] and [classifier]?
> Fixed resolver pattern for local ivy

- repl/src/main/scala/ammonite/repl/Main.scala
- repl/src/main/scala/ammonite/repl/Repl.scala
- repl/src/main/scala/ammonite/repl/Storage.scala
- repl/src/main/scala/ammonite/repl/Util.scala
- repl/src/main/scala/ammonite/repl/interp/ClassLoaders.scala
- repl/src/main/scala/ammonite/repl/interp/Compiler.scala
- repl/src/main/scala/ammonite/repl/interp/Evaluator.scala
- repl/src/main/scala/ammonite/repl/interp/Interpreter.scala
- repl/src/test/resources/scriptLevelCaching/QuickSort.scala
- repl/src/test/resources/scriptLevelCaching/fileToBeImported.scala
- repl/src/test/resources/scriptLevelCaching/ivyCacheTest.scala
- repl/src/test/resources/scriptLevelCaching/runTimeExceptions.scala
- repl/src/test/resources/scriptLevelCaching/scriptOne.scala
- repl/src/test/resources/scriptLevelCaching/scriptToBeLoaded.scala
- repl/src/test/resources/scriptLevelCaching/scriptTwo.scala
- repl/src/test/resources/scriptLevelCaching/testFileImport.scala
- repl/src/test/resources/scriptLevelCaching/testLoadModule.scala
- repl/src/test/scala/ammonite/repl/ScriptTests.scala
- repl/src/test/scala/ammonite/repl/TestRepl.scala
- repl/src/test/scala/ammonite/repl/ToolsTests.scala
Program flow is like:
Speed improvement is achieved by making processModule cache anything( scripts, predefs, imports including $ivy and $file,etc.) it processes at script level( at block level it already gets) and tries to retrieve from cache next time it is asked to process same code.
Process Module checks if the script is available in cacheFolder i.e. `scriptCaches`. If it is not found, processModule0 is called which keeps the rest of program flow same as before this diff but passes back importHooks and other imports accumulated in `processCorrectScript` function. This data is stored by `classFilesListSave` which takes list of `pkgName` concatenated with `wrapperName` and hash values of blocks along with imports and stores them.
If script is found in cache, `classFilesListLoad` reads …
> Implement script level cache

- sshd/src/main/scala/ammonite/sshd/SshdRepl.scala
- sshd/src/test/scala/ammonite/sshd/SshdReplTest.scala
This helps using the workaround from https://github.com/lihaoyi/Ammonite/issues/330 without having to create the predef file the server.
> Fix SshdRepl ignoring predef string

- amm/src/main/scala/ammonite/Main.scala
- amm/src/main/scala/ammonite/frontend/FrontEnd.scala
- amm/src/main/scala/ammonite/frontend/FrontEndUtils.scala
- amm/src/main/scala/ammonite/frontend/ReplAPI.scala
- amm/src/main/scala/ammonite/interp/Compiler.scala
- amm/src/main/scala/ammonite/interp/Evaluator.scala
- amm/src/main/scala/ammonite/interp/ImportHook.scala
- amm/src/main/scala/ammonite/interp/Interpreter.scala
- amm/src/main/scala/ammonite/interp/Preprocessor.scala
- amm/src/main/scala/ammonite/interp/Pressy.scala
- amm/src/main/scala/ammonite/interp/Storage.scala
- amm/src/main/scala/ammonite/main/Repl.scala
- amm/src/main/scala/ammonite/main/Scripts.scala
- amm/src/main/scala/ammonite/tools/Tools.scala
- amm/src/main/scala/ammonite/util/Parsers.scala
- amm/src/main/scala/ammonite/util/Util.scala
- amm/src/test/resources/scriptLevelCaching/scriptOne.sc
- amm/src/test/scala/ammonite/CachingTests.scala
- amm/src/test/scala/ammonite/ScriptTests.scala
- amm/src/test/scala/ammonite/TestRepl.scala
- amm/src/test/scala/ammonite/ToolsTests.scala
- amm/src/test/scala/ammonite/session/AdvancedTests.scala
- amm/src/test/scala/ammonite/session/BuiltinTests.scala
- amm/src/test/scala/ammonite/session/FailureTests.scala
- amm/src/test/scala/ammonite/session/ImportHookTests.scala
- amm/src/test/scala/ammonite/session/ProjectTests.scala
- appveyor.yml
- integration/src/test/scala/ammonite/integration/BasicTests.scala
- integration/src/test/scala/ammonite/integration/ErrorTruncationTests.scala
- integration/src/test/scala/ammonite/integration/LineNumberTests.scala
All integration and Amm tests except those which use `ivy`, or Syntax Error messages are passing. There are few tests in Amm/importHookTests having few windows path problems.
Syntax Error tests are failing on windows due to fastparse showing lesser number of characters as `\r\n` consume one extra character in the hard coded ` show 10 chars` thing in fastparse.
Ivy fails on windows as ivy settings for windows are different.
Major changes:
1) Change `splitScript` function in Preprocessor.scala to update `ncomment` variable with appropriate newlines and remove extra `\r` on windows. 
2) Update `\n` everywhere with `System.lineSeparator` defined as `newLine` in `Util.scala`
3) Modify test cases wherever necessary and guard those which can't pass now
4) Normalize newlines wherever reading from …
> Make most of  the amm tests and integration tests pass on Windows

- amm/src/main/scala/ammonite/interp/ClassLoaders.scala
- amm/src/main/scala/ammonite/interp/Storage.scala
- amm/src/test/scala/ammonite/CachingTests.scala
- amm/src/test/scala/ammonite/ScriptTests.scala
- amm/src/test/scala/ammonite/session/AdvancedTests.scala
- amm/src/test/scala/ammonite/session/BuiltinTests.scala
- amm/src/test/scala/ammonite/session/FailureTests.scala
- amm/src/test/scala/ammonite/session/ImportHookTests.scala
- amm/src/test/scala/ammonite/session/ProjectTests.scala
- appveyor.yml
- integration/src/test/scala/ammonite/integration/BasicTests.scala
- integration/src/test/scala/ammonite/integration/ErrorTruncationTests.scala
Major Changes:
1) To make the extended ascii character things defined in `scalaz` and similar other problems with `shapeless` we need to set encoding to `utf-8` on windows, for which I have set environment var on appveyor     `JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8`
2) There are no other major changes except one liners like 
```
private def jarSignature(url: URL) = {
-    val path = Path(url.getFile, root)
+    val path = Path(file.Paths.get(url.toURI()).toFile(), root)
```
3) Few ivy tests are behaving unusual on appveyor but thats just caching problem so I have made `appveyor.yml` itself a dependency for `.ivy2` cache so any major change in appveyor will redownload ivy. Though I am not sure if this change should merge into master.
4) I have introduced a `sanitizePath` function in …
> Make all amm and integration pass on windows except the Syntax Error ones

- amm/src/main/scala/ammonite/interp/Interpreter.scala
- integration/src/test/scala/ammonite/integration/BasicTests.scala
This PR is intended as a patch for https://github.com/lihaoyi/Ammonite/issues/418.
Before this PR any script having special chars in path name fails because while loadingClasses wrapperNames are encoded whereas while findClass is given non-encoded Name as argument. 
This PR fixes this issue.
> Make sure scripts with symbols in path name work

- amm/src/main/scala/ammonite/util/Util.scala
- amm/src/test/scala/ammonite/CachingTests.scala
- amm/src/test/scala/ammonite/ScriptTests.scala
- amm/src/test/scala/ammonite/TestUtils.scala
- readme/Footer.scalatex
This patch is a fix for https://github.com/lihaoyi/Ammonite/issues/417.
It avoids the case where `pathToPackage` throws unwanted exception when it can not find '.' in file name.
> Make scripts without extension throw correct exceptions

- amm/interp/src/main/scala/ammonite/runtime/Interpreter.scala
- amm/runtime/src/main/scala/ammonite/runtime/tools/IvyThing.scala
- amm/src/main/scala/ammonite/Main.scala
- integration/src/test/resources/ammonite/integration/basic/scalaTags.sc
- integration/src/test/resources/ammonite/integration/basic/wrongIvyCordinates.sc
- integration/src/test/scala/ammonite/integration/BasicTests.scala
Following repl session shows use of this diff
passing `-s` flag will make the ivy logs silent, though failures will still be thrown as Exception.
```
abhishek@abhishek-Inspiron-3542:~/Ammonite$ ./a i.sc 
:: loading settings :: url = jar:file:/home/abhishek/Ammonite/a!/org/apache/ivy/core/settings/ivysettings.xml
:: resolving dependencies :: com.lihaoyi#scalatags_2.11-caller;working
confs: [default]
found com.lihaoyi#scalatags_2.11;0.4.5 in central
found org.scala-lang#scala-library;2.11.4 in m2
found com.lihaoyi#acyclic_2.11;0.1.2 in central
found org.scala-lang#scala-compiler;2.11.0 in central
found org.scala-lang#scala-reflect;2.11.0 in central
found org.scala-lang.modules#scala-xml_2.11;1.0.1 in central
found org.scala-lang.modules#scala-parser-combinators_2.11;1.0.1 in m2
<a …
```
> `-s` cmd line switch makes ivy logs silent though failures will still be thrown as exception

- amm/interp/src/main/scala/ammonite/runtime/Interpreter.scala
- amm/repl/src/main/scala/ammonite/repl/Repl.scala
- amm/runtime/src/main/scala/ammonite/runtime/tools/IvyThing.scala
- amm/src/main/scala/ammonite/Main.scala
- integration/src/test/resources/ammonite/integration/basic/Failure.sc
- integration/src/test/scala/ammonite/integration/BasicTests.scala
Passing -s flag will make program output free from any noisy string not printed by the program itself eg. "Compiling ScriptName" printed when script is compiled instead of using from cache.
```
abhishek@abhishek-Inspiron-3542:~/Ammonite$ ./a i.sc
Compiling Main.sc
Compiling Main.sc
Compiling Main.sc
Compiling Main.sc
Compiling Main.sc
Compiling i.sc
Hello
abhishek@abhishek-Inspiron-3542:~/Ammonite$ 
```
```
abhishek@abhishek-Inspiron-3542:~/Ammonite$ rm ~/.ammonite/cache/ -rf
abhishek@abhishek-Inspiron-3542:~/Ammonite$ ./a i.sc -s
Hello
```
Besides this -s also makes ivy silent
> Make output silent with -s flag

- amm/interp/src/main/scala/ammonite/runtime/Compiler.scala
- amm/src/test/scala/ammonite/session/AdvancedTests.scala
Which was caused by the presence of both normal and source jars on the classpath and led to behaviour like this:
```
@ interp.load.plugin.ivy("org.scalamacros" % "paradise_2.11.7" % "2.1.0")
@ var x = 1
cmd2.sc:2: both org.scalamacros.paradise.typechecker.AnalyzerPlugins$MacroPlugin$@4e3931 and org.scalamacros.paradise.typechecker.AnalyzerPlugins$MacroPlugin$@409e0e69 want to enter a symbol for this tree
package $sess
^
scala.reflect.internal.Types$TypeError: both org.scalamacros.paradise.typechecker.AnalyzerPlugins$MacroPlugin$@4e3931 and org.scalamacros.paradise.typechecker.AnalyzerPlugins$MacroPlugin$@409e0e69 want to enter a symbol for this tree
scala.tools.nsc.typechecker.Contexts$ThrowingReporter.handleError(Contexts.scala:1402) …
```
> Fix compiler plugin instance duplication

- ops/src/main/scala/ammonite/ops/Path.scala
- shell/src/main/scala/ammonite/shell/ShellSession.scala
- shell/src/test/scala/ammonite/shell/SessionTests.scala
- Adding a method `Path#followLinks` that follows symlinks transitively (if the Path is a symlink).
- Fixing `cd` so that you can go to a symlinked directory.
This fixes issue https://github.com/lihaoyi/Ammonite/issues/432
> [Issue 432] Follow links when executing `cd`

- destSymLink
- ops/src/main/scala/ammonite/ops/Model.scala
- shell/src/main/scala/ammonite/shell/ShellSession.scala
- shell/src/test/scala/ammonite/shell/SessionTests.scala
This is a proposal to fix #432 via the mechanism of resolving 'real paths' + following symlinks (as described by the `j.n.f.Path`'s javadoc (https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#toRealPath-java.nio.file.LinkOption...-)). 
Also fixes the bug which caused the `stat.full` on the `root` variable to fail.
Test included.
> Fix #432 (Can't cd into directories' symlinks)

- ops/src/main/scala/ammonite/ops/Path.scala
- ops/src/test/scala/test/ammonite/ops/PathTests.scala
- shell/src/main/scala/ammonite/shell/ShellSession.scala
- shell/src/test/scala/ammonite/shell/SessionTests.scala
I think `cd! symlinkedDir` should actually change into a symlinked directory and not into the directory the symlink points to.
As it is now, `tmp` is symlinked on a Mac OS X, and you can't do something like this:
```
cd! root/'tmp
ls! up/'home // "up" does not point to root
```
This PR makes `cd` change to the symlinked directory (if it exists).
This PR also adds `Path#tryFollowLinks : Option[Path]`, which will return the link target (if it exists).
> add "Path#tryFollowLinks"; "cd" will now change to symlinked directory

- readme/Sample.scala
There's no need to error on failing to create ~/.ammonite if it already exists, such as for those who have already downloaded Ammonite.
> `mkdir -p` to make instructions work in any order (tiny change)

- amm/interp/src/main/scala/ammonite/runtime/Pressy.scala
- amm/src/test/scala/ammonite/AutocompleteTests.scala
#430 describes a case when we ask for completion on an invalid input and `ammonite.runtime.Pressy.Run#prefixed` throws NPE and the whole REPL goes down.
The fix is basically to lift the `prefixed` call into a Try context that is already there.
> Fix + test for #430

- terminal/src/main/scala/ammonite/terminal/filters/BasicFilters.scala
#397 was about accepting pipe's input.
The problem as I saw it was in the fact that `-1` designating EOF of Java's input streams was accepted by an incorrect filter. 
There was this weird thing, first stating that exit is done by encountering a `-1` in a stream supplying _ints_, then designating a pattern of `(-1).toChar.toString` instead (which was a single string of `0xffff` char since `Char[acter]`s are unsigned), then (@ Filter.scala:48) did `prefix.map(_.toInt)`, which resulted in `0xffff` again, which, of course, didn't match `-1` (int) in `LazyList#dropPrefix`.
I propose an implementation which avoids this casting, which makes an original example work (both on mac OS and Linux, but that's kinda irrelevant since the problem is not in the piping mechanisms after all).
No unit tests …
> [WIP]Attempt to fix #397

- amm/interp/src/main/scala/ammonite/runtime/Interpreter.scala
- integration/src/test/scala/ammonite/integration/ErrorTruncationTests.scala
- integration/src/test/scala/ammonite/integration/LineNumberTests.scala
Hi,
this is my stab at #493. I took your advice and tracked the calls to this point in `Interpreter.scala`. But… I'm not quite sure if that is the correct place; or all of them. Also, I left the case for `ImportHook.Source.Url` unchanged, but maybe it is sensible to have a full url here, too? I thought an url as return value for `File()` looks strange. And to be honest,  I don't really understand what the url case means. 
I tested with the result of `amm/test:assembly`.
> pass full path to script being compiled

- sshd/src/main/scala/ammonite/sshd/SshServer.scala
- sshd/src/test/scala/ammonite/sshd/SshTestingUtils.scala
OpenSSH 7.x deprecated DSA keys, requiring them now to be explicitly allowed via the "HostKeyAlgorithms" option. For more info, see:
https://www.openssh.com/releasenotes.html#7.0
http://security.stackexchange.com/questions/112802/why-openssh-deprecated-dsa-keys
As the SSH daemon most often will be used on localhost, it will often be used with the OpenSSH client. The slow upgrade process of enterprise distros has left OpenSSH on 6.x, but this has already changed for Ubuntu 16.04 LTS, and the next versions of Debian & RHEL will be 7.x too.
This patch resolves this problem by replacing DSA with RSA (which has wider compatibility than elliptic curve) for key generation.
Tests have also been modified so the client only uses host key algorithms that both appear in the JSch supported algorithms …
> Use RSA host keys instead of DSA

- sshd/src/main/scala/ammonite/sshd/SshdRepl.scala
This allows the server to be used in environments with hot-reloading, like the Play Framework development server.
> Allow configuration of SSHD console classloader

- .gitignore
- terminal/src/main/scala/ammonite/terminal/filters/ReadlineFilters.scala
- terminal/src/test/scala/ammonite/terminal/EditTests.scala
#514 
Didn't want to completely scrap the old behavior. I intended this change to re-map the old behavior to `Ctrl-Shift-k` (i.e. `Ctrl-K` (uppercase)) and replace the old `Ctrl-k` with zsh-style "delete to next newline" behavior. 
Wasn't sure how to test locally to confirm that simply upcasing the `k` would have that desired effect though?
> Ctrl-u/Ctrl-k cut to the beginning/end of line

- integration/src/test/resources/ammonite/integration/basic/HttpApi.sc
- integration/src/test/scala/ammonite/integration/BasicTests.scala
An attempt to remove this annoying error. I replaced github api  with [jsonplaceholder](http://jsonplaceholder.typicode.com/) ,which has no rate limits.
> Avoid github exceeded API rate limit error in tests

- readme/Cookbook.scalatex
- readme/Footer.scalatex
- readme/Repl.scalatex
- readme/Scripts.scalatex
Just fixed remaining .scala extensions and removed trailing white-spaces.
Looks like you already did all necessary docs changes for #558.  But if there is still something I could help with, please let me know.
> Minor docs fixes

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/runtime/src/main/scala/ammonite/runtime/InterpAPI.scala
- readme/Scripts.scalatex
Add an overloaded version of `LoadJar.cp` that takes a sequence of paths for efficiency. In testing performance adding 226 jars, the overloaded version is about two orders of magnitude faster than the original method.
Also, trim some EOL whitespace and add an EOF newline (BSR)
> Add an overloaded version of LoadJar.cp that takes a sequence of paths

- ops/src/main/scala/ammonite/ops/Shellout.scala
Whilst waiting for IO Shellout.executeStream was running a tight loop and consuming significant
amounts of CPU.  Adding a small sleep when no input was seen reduces cpu usage significant.
> Add a sleep in Shellout.executeStream to reduce spinning.

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/repl/src/main/scala/ammonite/repl/ApiImpls.scala
- amm/repl/src/main/scala/ammonite/repl/Repl.scala
- amm/repl/src/main/scala/ammonite/repl/ReplAPI.scala
- amm/src/main/scala/ammonite/Main.scala
inspired by #121 but not exactly what we were discussing there
not sure if this is the best (or even a good 😅 ) way to do this
but really just wanted something that worked [like this](https://github.com/emanresusername/.ammonite/blob/akkators/predef.sc#L112-L125) and this handled that usecase well enough for me :)
glad to hear other thoughts/suggestions/improvements/etc
> add beforeExitHooks for cleanup before repl exits

- readme/Scripts.scalatex
Keeps it consistent with the earlier example and 7.1.1 isnt publish for scala 2.12.
> Update example to scalaz 7.2.7

- amm/runtime/src/main/scala/ammonite/runtime/Storage.scala
When running the same script in parallel, often several instances fail due to a `FileAlreadyExistsException` (e.g. see below).
This PR wraps the relevant code in a try/catch that ignores this exception. Thanks for your consideration.
```
Exception in thread "main" java.nio.file.FileAlreadyExistsException: /home/abilge/.ammonite/cache/0.8.1/scriptCaches/$file.proposals/f322036cad9afef1f1b0c6ce46b2d2f6/classFilesOrder.json
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProv …
```
> Ignore FileAlreadyExistsException when caching script

- .travis.yml
- amm/src/test/scala/ammonite/session/EulerTests.scala
The `p25` test of `EulerTests` seems not to compile anymore in `2.12.2` (haven't investigated why... - changes in the typer?). This PR fixes it, and makes the CI use `2.12.2`.
> Fix test in 2.12.2

- readme/Cookbook.scalatex
Updated docs to make sure that HTTP Requests example compiles with Scala 2.12
> Cookbook HTTP Requests update scalaj-http to work with scala 2.12.x

- .travis.yml
- appveyor.yml
- build.sbt
2.14.3 is the latest bug fix release for 2.x.x branch. Update to 3.x.x branch isn't possible as it requires Java 8.
Assembly workaround is not needed any more, cause now jline versions in Scala  2.11.11, 2.12.x and Ammonite are the same.
> Update jline to 2.14.3

- integration/src/test/resources/ammonite/integration/basic/Spark2.json
- integration/src/test/resources/ammonite/integration/basic/Spark2.sc
The idea is to use SparkSession for Spark integration example as it's more idiomatic way in Spark 2.
> Make Spark2 example more idiomatic

- shell/src/main/resources/ammonite/shell/example-predef.sc
After downloading new predef introduced in 0.9.5 I get:
```
.ammonite/predef.sc:3: object Properties is not a member of package ammonite.util
s"ammonite-shell_${util.Properties.versionNumberString}" %
```
There is difference between example-predef.sc and example-predef-bare.sc
> Fix object Properties is not a member of package ammonite.util in example-predef.sc

- amm/src/main/scala/ammonite/main/Scripts.scala
- amm/src/test/scala/ammonite/main/MainTests.scala
@doc annotations for main methods are described in documentation.  Everything is already in place to process them, but they're not displayed in the usage.
With this change, those docs are included on the line following the method name.
> Include @doc annotations for main methods in usage

- readme/Scripts.scalatex
I originally confused the use of `@` in docs as part of the formatting for the README.
This snippet should make it clear that 
* it's code
* it's required
Inspired by my errant bug here: https://github.com/lihaoyi/Ammonite/issues/546
> make the required use of ampersand a bit clearer in docs

- readme/Repl.scalatex
Update docs to match changes introduced in 0.7.2:
Changed the syntax for import $file segments outside your current directory from import $file.`..`.foo to import $file.^.foo. This makes it a lot shorter and mitigates a problems caused by the file-name being too long.
Instead of introducing second version of parent separator as in https://github.com/lihaoyi/Ammonite/pull/504
Aligned with current implementation:
https://github.com/lihaoyi/Ammonite/blob/master/amm/util/src/main/scala/ammonite/util/Util.scala#L13
> Fix import file docs to reflect changes to parent dir introduced in 0.7.2

- terminal/src/main/scala/ammonite/terminal/SpecialKeys.scala
- terminal/src/main/scala/ammonite/terminal/filters/ReadlineFilters.scala
Same issue as #152 but for urxvt. It emits `^[[7~` for Home and `^[[8~` for End.
By the way you can use your favorite Linux distro `/etc/inputrc` as a reference. Here is one from my Arch Linux: https://gist.github.com/aolshevskiy/cd4113179e22e1a831b65276614611de
Here is an excerpt with relevant screen and urxvt keycodes:
```
"\e[1~": beginning-of-line
"\e[4~": end-of-line
...
"\e[7~": beginning-of-line
...
"\e[8~": end-of-line
```
And one more thing: you're doing great work here! Cheers :clap:
> Fix home, end keys in urxvt

- sshd/src/main/scala/ammonite/sshd/SshdRepl.scala
Fixes #659.
`Main` contains a lot of initialization code, without which the wrapped `repl.Repl` is not usable. In this case, initializing `repl.ReplBridge.value`.
> Use Main instead of repl.Repl in Sshd. This is a temporary fix for #659

- amm/src/test/scala/ammonite/session/EvaluatorTests.scala
- amm/util/src/main/scala/ammonite/util/Model.scala
- readme/Footer.scalatex
> fix for Ammonite does not properly backtick a value #663

- ops/src/main/scala/ammonite/ops/FileOps.scala
- ops/src/main/scala/ammonite/ops/Model.scala
- ops/src/main/scala/ammonite/ops/Path.scala
- ops/src/main/scala/ammonite/ops/PathUtils.scala
- ops/src/main/scala/ammonite/ops/Shellout.scala
- ops/src/main/scala/ammonite/ops/package.scala
- Replace collection.JavaConversions with collection.JavaConverters
- Remove unused import statements
- Replace .length > 0 by .nonEmpty
- Replace getOrElse(null) with .orNull on option
- Remove `new` on case classes
> Small clean up in ammonite.ops

- ops/src/main/scala/ammonite/ops/FileOps.scala
- ops/src/test/scala/test/ammonite/ops/OpTests.scala
- readme/Footer.scalatex
Attempt to fix https://github.com/lihaoyi/Ammonite/issues/679
For now without tests, but I'll try to figure our reliable way to verify it on travis.
1) Bare minimum would be to check if directory with no access doesn't throw Exception and we get empty LsSeq
2) Better would be to have directory with at least file inaccessible file and check if we get non empty LsSeq
Maybe we can use /tmp
> ls.rec handle inaccessible files

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/src/test/scala/ammonite/unit/ParserTests.scala
The [NixOs](https://nixos.org/) nix-shell commonly uses multiple shebang lines.  This pull request enables parsing of multiple shebang lines.
> enable parsing of multiple shebang lines for nix-shell

- build.sbt
- project/plugins.sbt
It look like it fixes #664.
```
@ import $ivy.`org.apache.jena:apache-jena-libs:3.1.1` 
@ import org.apache.jena.rdf.model._ 
import org.apache.jena.rdf.model._
@ import org.apache.jena.util.FileManager; 
import org.apache.jena.util.FileManager;
@ val model = ModelFactory.createDefaultModel(); 
model: Model = <ModelCom   {} | >
```
Sources still fail during resolution:
```
Failed to load source dependencies
not found: https://repo1.maven.org/maven2/org/apache/jena/apache-jena-libs/3.1.1/apache-jena-libs-3.1.1-sources.jar
```
> Update coursier to 1.0.0-RC10

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/repl/src/main/scala/ammonite/repl/Repl.scala
- amm/runtime/src/main/scala/ammonite/runtime/Evaluator.scala
- amm/src/main/scala/ammonite/Main.scala
- amm/src/test/scala/ammonite/TestRepl.scala
- amm/src/test/scala/ammonite/TestUtils.scala
- amm/src/test/scala/ammonite/interp/PrintTests.scala
- amm/util/src/main/scala/ammonite/util/Model.scala
- amm/util/src/main/scala/ammonite/util/Res.scala
This PR adds an extra field `resultStream` to `Printer`, and uses it solely to print the "result" of the user code (like `n: Int = 2` if the user entered `val n = 1 + 1`).
If one uses Ammonite via its API, that allows to get specifically these results, rather than whatever else can be printed via `outStream`. It's useful when these results are then treated in a specific way.
> Add output stream for results

- readme/Repl.scalatex
was just browsing through the site today and notice the `AmmoniteBridge` section had appeared since i last checked in and figured i'd update this section to follow that 
came up in a random other project i was working on and wanted to use the `--no-home-predef` flag to eliminate some variables and saw that didn't work with the `Main().run()` version 😢 
couple questions
0. is there some larger (bad) implication to doing this globally such that it should remain the way it is now
0. if not. should i just put `@hl.ref('integration/'src/'test/'scala/'ammonite/'integration/"AmmoniteBridge.scala")` inside the `"""`s there like [here](https://github.com/lihaoyi/Ammonite/blob/5dc7e0b8102832515d57aa548e282d5437dcea08/readme/Scripts.scalatex#L749) just to keep those sections always in sync?
> sync existing sbt project integration with bridge docs

- amm/repl/src/test/scala/ammonite/TestRepl.scala
This is useful while debugging or changing things in the internals of Ammonite. Previously, errors during predefs where trapped. Now they are loudly reported.
> Report predef initialization error during tests

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/repl/src/main/scala/ammonite/repl/ApiImpls.scala
- amm/repl/src/main/scala/ammonite/repl/Repl.scala
- amm/repl/src/test/scala/ammonite/TestRepl.scala
- amm/repl/src/test/scala/ammonite/TestUtils.scala
- amm/repl/src/test/scala/ammonite/session/BuiltinTests.scala
- amm/runtime/src/main/scala/ammonite/runtime/ClassLoaders.scala
- amm/src/main/scala/ammonite/Main.scala
Rather than failing at runtime with ClassNotFoundException.
This makes the last command in the following fail at compile time, rather than at runtime with a ClassNotFoundException:
```scala
@ repl.sess.save("foo")
@ val a = repl.sess.load("foo")
@ a
```
Although this looks like a detail here, this is required for classwrapping (upcoming PR).
It works by "freezing" the current frame after loading a session, preventing it to accept extra imports. That way, no imports from the command that loaded the session are added, and we can't run into ClassNotFoundException about it.
> Discard load command result

- .travis.yml
- appveyor.yml
- ci/build.sc
- readme/Footer.scalatex
The latest 2.11.x, 2.11.12, contains a CVE fix for the compilation daemon as well as a number of other bug fixes.
For more info see [the 2.11.12 release notes](https://github.com/scala/scala/releases/tag/v2.11.12).
> Bump from 2.11.11 to 2.11.12

- amm/interp/src/main/scala/ammonite/interp/AmmonitePlugin.scala
- amm/interp/src/main/scala/ammonite/interp/Compiler.scala
- amm/interp/src/main/scala/ammonite/interp/CompilerLifecycleManager.scala
- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/interp/src/main/scala/ammonite/interp/Parsers.scala
- amm/interp/src/main/scala/ammonite/interp/Preprocessor.scala
- amm/repl/src/main/scala/ammonite/repl/ApiImpls.scala
- amm/repl/src/main/scala/ammonite/repl/Repl.scala
- amm/repl/src/main/scala/ammonite/repl/ReplAPI.scala
- amm/repl/src/test/scala/ammonite/DualTestRepl.scala
- amm/repl/src/test/scala/ammonite/TestRepl.scala
- amm/repl/src/test/scala/ammonite/interp/AutocompleteTests.scala
- amm/repl/src/test/scala/ammonite/interp/PrintTests.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
- amm/repl/src/test/scala/ammonite/session/BuiltinTests.scala
- amm/repl/src/test/scala/ammonite/session/EulerTests.scala
- amm/repl/src/test/scala/ammonite/session/EvaluatorTests.scala
- amm/repl/src/test/scala/ammonite/session/FailureTests.scala
- amm/repl/src/test/scala/ammonite/session/ImportHookTests.scala
- amm/repl/src/test/scala/ammonite/session/ImportTests.scala
- amm/repl/src/test/scala/ammonite/session/ProjectTests.scala
- amm/repl/src/test/scala/ammonite/session/SerializationTests.scala
- amm/runtime/src/main/scala/ammonite/runtime/ClassLoaders.scala
- amm/runtime/src/main/scala/ammonite/runtime/Evaluator.scala
- amm/runtime/src/main/scala/ammonite/runtime/ImportHook.scala
- amm/runtime/src/main/scala/ammonite/runtime/Storage.scala
The goal of this PR is to make Ammonite behave well wrt Java serialization. This is a quite big PR, hard to split in smaller ones, that roughly adds a failing test (`SerializationTests`), then makes it pass.
Its goal, in sessions like this one
```
@ val n = 2
n: Int = 2
@ val f: Int => Int = { p =>
p + n
}
f: Int => Int = <function1>
```
is to be able to serialize `f` with [Java serialization](https://docs.oracle.com/javase/7/docs/api/java/io/ObjectInputStream.html), without its deserialization to re-trigger the calculation of the values `f` depends on (`n`) - these should be serialized / deserialized along with `f`.
Currently, the user code is wrapped in a singleton. Singletons don't serialize their fields, and re-compute them if needed upon deserialization. So here, `n` would be …
> Class wrapper for Java serialization friendliness

- amm/src/main/scala/ammonite/main/Cli.scala
Current behavior:
```
$ amm -b ""
Loading...
@
```
I think following is desired behavior.
```
$ amm/target/amm -b "" 
Loading...
@
```
> Empty welcome banner should not be printed

- amm/repl/src/main/scala/ammonite/repl/AmmoniteFrontEnd.scala
We decide to filter out all methods that comes with Any.
There was two options. One to edit Pressy.scala:57:
```scala
blacklist(s.fullNameAsName('.').decoded) ||
s.fullNameAsName('.').decode.startsWith("scala.Any.") || //this line
s.isImplicit ||
```
but then when people'll press tab then it'll never complete into full name (eg ".toString") even if it is the only option.
And changes mede here.
They'll be completed when it is the only option and show also definitions after second `Tab`.
> autocomplete: blacklisted anything that comes from Any

- build.sbt
fixes #745 and #762.
I could be wrong, but I think that L354 might need the same path ``(packageBin in (shell, Compile))`` as well.
> Add AMMONITE_TEST_SHELL env var for proper doc building

- amm/interp/src/main/scala/ammonite/interp/CompilerLifecycleManager.scala
- amm/interp/src/main/scala/ammonite/interp/InterpAPI.scala
- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/src/test/resources/scriptCompilerSettings/configureCompiler.sc
- amm/src/test/resources/scriptCompilerSettings/preConfigureCompiler.sc
- amm/src/test/scala/ammonite/interp/CompilerSettingsTests.scala
Adds a preConfigureCompiler method to the InterpAPI, allowing to mutate settings in a way that is applied before the interpreter instantiates its next compiler.
> Adds preConfigureCompiler to the interpreter

- .travis.yml
- amm/runtime/src/main/scala/ammonite/runtime/Classpath.scala
- ci/upload.sc
- integration/src/test/resources/some-dummy-library/project/build.properties
Fixed `Classpath.classpath` on some situation when Ammonite is used on Java 9 as a non-assembly jar (e.g., `mill dev.assembly`).
Changed `.travis.yml` to use `amm` for testing since `amm` now runs on Java 9.
> Java 9 non-assembly fix and only use amm for testing in travis

- .gitignore
- amm/interp/src/main/scala/ammonite/interp/AmmonitePlugin.scala
- amm/src/test/resources/scriptCompilerSettings/yRangepos.sc
- amm/src/test/resources/scriptCompilerSettings/yRangeposError.sc
- amm/src/test/scala/ammonite/interp/YRangeposTests.scala
* Adds logic to shift the point in range positions (it does not shift start / end because of some internal validation that crashes the compilation)
* Shares the source file trimming between nodes for optimisation
Rationale : 
When compiling ammonite script with `YrangePos` enabled, the transformation performed in the AmmonitePlugin was discarding the "range" nature of the position. This allows to conserve range information, which improves interoperability with some compiler plugins.
> Added logic to avoid losing range information

- amm/interp/src/main/scala/ammonite/interp/CompilerLifecycleManager.scala
- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/runtime/src/main/scala/ammonite/runtime/Classpath.scala
- amm/runtime/src/main/scala/ammonite/runtime/Storage.scala
This PR re-introduces Java 9 rt.jar caching from #761 that I removed due to memory leaks in Ammonite tests.
The main difference is that it now avoids caching rt.jar if the storage backend is in a temp directory, which is detected based on `System.getProperty("java.io.tmpdir")`. This temp directory caching avoidance sidesteps the memory leaks in Ammonite tests, which mostly use temp dir storage backend (and some `Storage.InMemory`). The heuristics for avoiding caching in `rtCacheDir ` can be changed in the future to cover more (or different) cases.
This finally fixes #675.
> Java 9 rt.jar caching redux

- amm/repl/src/main/scala/ammonite/repl/FrontEnd.scala
- amm/repl/src/main/scala/ammonite/repl/Repl.scala
- amm/repl/src/test/scala/ammonite/interp/AutocompleteTests.scala
- build.sbt
Logic rewritten to use JLine3 API. Some notable improvements:
- **autocomplete** behaves like tabindex, you can select it 😲 
- **multiline** editing works awesome
- **multiline** pasting works 
- **multiline** string inserts TAB instead of doing autocomplete (when blank line)
- **highlighting** works fine
- opening paren/bracket even **blinks** when you close a paren, OMG
- Ctrl+Left/Ctrl+Right skips a word
Tests are passing, except `ops/test`? Seems unrelated, fails on other PRs also...
> [WIP] Update JLine to v3

- amm/runtime/src/main/scala/ammonite/runtime/Classpath.scala
This PR adds creation of Java 9 rt cache dir for robustness.
While Ammonite creates its home directory used for caching rt.jar before `Classpath.classpath` is called, mill, however, does not. It is safer to fix the issue here by removing any assumption on the existence of rt cache directory.
> Always create Java 9 rt cache dir

- build.sbt
- project/plugins.sbt
- readme/Footer.scalatex
- readme/Sample.scala
This pr changes updates the generated universal script to be on par with lihaoyi/mill#264.
Also the shebang line isn't generated anymore by default so that it doesn't show an error on windows anymore.
The linux download instructions should be updated to add this line afterwards.
> Updated universal script and removed shebang line by default

- .travis.yml
__oraclejdk7 setting has no meaning!__
travis-ci no longer support oraclejdk7. travis-ci still support openjdk7 but openjdk7 build fail
- https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879
- https://github.com/lihaoyi/Ammonite/issues/774
- https://github.com/lihaoyi/Ammonite/pull/740
> use oraclejdk8 instead of oraclejdk7

- amm/repl/src/test/scala/ammonite/unit/SourceTests.scala
- amm/runtime/src/main/scala/ammonite/runtime/tools/IvyThing.scala
- build.sc
Coursier no longer depends on scalaz as of 1.1.0-M4. Removing scalaz
means smaller bundle size and keeping interpreter classpath more
pristine.
> Removes dependency on scalaz (#644)

- amm/src/main/scala/ammonite/main/Router.scala
- amm/src/test/resources/mains/ArgList.sc
- amm/src/test/scala/ammonite/main/MainTests.scala
The issue, #747, is caused by testing the first character (value(0)) for '-', without checking whether it is empty or not.  This fix replaces that check with '.startsWith("-")', which works with an empty string just fine.  There is a unit test for the fix which, without the fix, reproduces the behavior of the issue.
> Issue 747: Switched to startsWith() method to prevent exception

- .travis.yml
- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/repl/src/main/scala/ammonite/main/Defaults.scala
- amm/repl/src/main/scala/ammonite/repl/Repl.scala
- amm/repl/src/test/scala/ammonite/TestRepl.scala
- amm/repl/src/test/scala/ammonite/TestUtils.scala
- amm/repl/src/test/scala/ammonite/session/FailureTests.scala
- amm/repl/src/test/scala/ammonite/session/ProjectTests.scala
- amm/src/main/scala/ammonite/Main.scala
- appveyor.yml
- build.sc
This PR adds a few tricks to try not to load several versions of a given dependency.
It doesn't cover all cases (one can always load newer versions of already loaded stuff), and doesn't try to warn users in case something wrong was prevented (if users add a newer version of something already in Ammonite itself, this PR prevents it to be loaded - silently).
In more details, the first commit tries to prevent loading JARs that are already in Ammonite itself. It generates a resource file (`ammonite-deps.txt`), listing all the dependencies of Ammonite as known from sbt. It then excludes these dependencies from resolutions, so that no newer or older versions of those can be loaded again.
Second commit is just some refactoring for the next one.
Third commit tries not to load JARs for previous …
> Try not to load duplicated JARs if possible

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/repl/src/main/scala/ammonite/repl/ApiImpls.scala
- amm/repl/src/test/scala/ammonite/TestRepl.scala
- amm/repl/src/test/scala/ammonite/TestReplBridge.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
- amm/runtime/src/main/scala/ammonite/runtime/ClassLoaders.scala
This PR adds a bridge in `TestRepl`, and ensures it can be used from the user code. For the test to be green, this required to pass the extra bridge class names to `SpecialClassLoader`, so that it can special case them too (like it does for the default Ammonite bridges).
> Fix custom bridges handling

- amm/repl/src/main/scala/ammonite/repl/FrontEnd.scala
- amm/repl/src/main/scala/ammonite/repl/FrontEndUtils.scala
Fixes #817, #823.  
Cursor now behaves correctly. Please report if there are still issues with it.  
I still couldn't figure out why it doesn't accept a candidate when there are braces at the end (assume `|` is cursor): `x.toSt|()` (but it stays there now.. xD).
When you hit `Enter` now, it will only accept the input when cursor is at the end.
There's also a fix in `FrontEndUtils` for `width` and `height`, I forgot when the exception was happening...
> Fix jline autocomplete

- amm/repl/src/test/scala/ammonite/session/ProjectTests.scala
- amm/runtime/src/main/scala/ammonite/runtime/tools/IvyThing.scala
Artifacts returned by coursier have a type attached to them. Only a subset of those
are JARs that are relevant to us here. Without this PR, test jars or zip files could
be unnecessarily added to the classpath.
> Don't add stuff with wrong artifact types to the classpath

- amm/interp/src/main/scala/ammonite/interp/CompilerLifecycleManager.scala
Fixes #752 and hopefully some other encoding related errors. E.g. I was getting this one when trying to use shapeless:
```
IO error while decoding cmd1.sc with UTF-8 
Please try specifying another one using the -encoding option
```
> Use UTF-8 when compiling sources

- amm/interp/src/main/scala/ammonite/interp/Pressy.scala
- amm/repl/src/test/scala/ammonite/interp/AutocompleteTests.scala
Fixes #861.
First-time contributor, apologies in advance 😄 
1. This includes a hack to leverage protected backquoting method in scala-compiler. Arguably better to just re-implement the backquoting rules in Ammonite until they're exposed more-accessibly upstream.
2. I stumbled upon a dubious prior behavior. Prior to my changes:
a. `val x = new { val foo = 1 }; x.<caret>` completed as `"foo"`
b. `object x { val foo = 1 }; x.<caret>` completed as `"foo "` (note trailing space)
I tracked this back to the a Scala implementation detail called LOCAL_SUFFIX_STRING which seems to have [caused head-scratching for others](https://github.com/scala/bug/issues/5736).
I had to strip this whitespace to avoid having the trailing space trigger back-quoting unnecessarily.
There's a risk that users' muscle …
> Support auto-complete of back-quoted symbols.

- amm/interp/src/main/scala/ammonite/interp/Pressy.scala
https://github.com/lihaoyi/Ammonite/pull/863 uses stuff not available in scala-reflect < 2.11.8, which broke [one of the *release* jobs](https://travis-ci.org/lihaoyi/Ammonite/jobs/428887990) that builds Ammonite against pre 2.11.8 scala versions. This PR fixes that.
> Fix pre scala 2.11.8 builds

- readme/Scripts.scalatex
#825 points bad link in the documentation for uPickle library.
This PR address this issue.
> fix link to the upickle

- amm/interp/src/main/scala/ammonite/interp/Preprocessor.scala
Use our standard `literalize` functions rather than just quoting and hoping.
There are probably other places this needs to happen but let's just do this for now
Fixes https://github.com/lihaoyi/Ammonite/issues/882
> Properly escape identifiers when generating wrapper code

- amm/interp/src/main/scala/ammonite/interp/CompilerLifecycleManager.scala
- amm/interp/src/main/scala/ammonite/interp/Pressy.scala
Like https://github.com/lihaoyi/Ammonite/pull/891, but without an extra method to also access it via `ReplAPI`. See the discussion in https://github.com/lihaoyi/Ammonite/pull/891 for the issues this triggers.
> Make Pressy and its compiler accessible

- amm/runtime/src/main/scala/ammonite/runtime/Storage.scala
Possible fix for #895
When reading the cached IvyMap, check that the jar files actually exist. Filtering based on their existence allows `Ammonite` to simply re-download them if something has happened to one of the `jars`
> Check that cached ivy dependencies exist

- amm/interp/src/main/scala/ammonite/interp/Preprocessor.scala
Inspired by [scalafmt rule](https://scalameta.org/scalafmt/docs/configuration.html#redundantparens)
> simple refactor: remove unneeded parentheses in if guard

- amm/interp/src/main/scala-2.11/ammonite/interp/GlobalInitCompat.scala
- amm/interp/src/main/scala-2.12/ammonite/interp/GlobalInitCompat.scala
- amm/interp/src/main/scala-2.12/scala/tools/nsc/CustomZipAndJarFileLookupFactory.scala
- amm/interp/src/main/scala/ammonite/interp/Compiler.scala
- amm/interp/src/main/scala/ammonite/interp/InterpAPI.scala
- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/interp/src/main/scala/ammonite/interp/Pressy.scala
- amm/interp/src/main/scala/ammonite/interp/internal/CustomURLZipArchive.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
- amm/repl/src/test/scala/ammonite/session/ProjectTests.scala
- amm/runtime/src/main/scala/ammonite/runtime/ClassLoaders.scala
- amm/runtime/src/main/scala/ammonite/runtime/Classpath.scala
- amm/runtime/src/main/scala/ammonite/runtime/Storage.scala
~*Not sure I'd like that to be merged yet*, but weighting in / out welcome~
Motivation for that PR is to have Ammonite be fine with unusual setups, where the initial classpath isn't necessarily made entirely of files, but could be made of more general `java.net.URL`s.
For now, Ammonite assumes its initial classpath [is made of files](https://github.com/lihaoyi/Ammonite/blob/c4ab4986cd950ae2efd6e97b56d212db7cfe050c/amm/runtime/src/main/scala/ammonite/runtime/Classpath.scala#L27). This PR keeps that classpath as URLs a bit longer. If a URL doesn't correspond to a file, a `scala.reflect.io.URLZipArchive` rather than a [`scala.reflect.io.FileZipArchive`](https://github.com/lihaoyi/Ammonite/blob/c4ab4986cd950ae2efd6e97b56d212db7cfe050c/amm/interp/src/main/scala-2.11/ammonite/interp/GlobalInitCo …
> Allow non-files in classpath

- amm/runtime/src/main/scala/ammonite/runtime/Storage.scala
When running `amm` for the first time after installation, sometimes I got this error (on Archlinux and Ubuntu 16.04)
```
Exception in thread "main" java.nio.file.NoSuchFileException: /home/kien/.ammonite/session
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
at java.nio.file.Files.newByteChannel(Files.java:361)
at os.write$.write(ReadWriteOps.scala:61)
at os.write$over$.apply(ReadWriteOps.scala:137)
at ammonite.runtime.Storage$Folder.getSessionId(Storage.scala:132)
at ammonite.Main.run(Main.scala:185)
at …
```
> Create session directory if not exists

- amm/repl/src/main/scala/ammonite/repl/Repl.scala
- terminal/src/main/scala/ammonite/terminal/Terminal.scala
This partly reverts https://github.com/lihaoyi/Ammonite/commit/84d48542654285a9268964e4571fe0a91ef335d8. See the commit message some details.
I guess the optimizations of https://github.com/lihaoyi/Ammonite/commit/84d48542654285a9268964e4571fe0a91ef335d8 could be added back more carefully in the future. (AFAIU, it basically needs to pass Ctrl-C to the code that reads input, and save / restore terminal state right before the user code runs external commands, like in https://github.com/lihaoyi/Ammonite/issues/922).
Fix https://github.com/lihaoyi/Ammonite/issues/920.
Fix https://github.com/lihaoyi/Ammonite/issues/922.
> Fix back some tty-related stuff

- amm/interp/src/main/scala/ammonite/interp/Preprocessor.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
- readme/Footer.scalatex
Previously, private things were printed back, even though they can't be used after the input block they're defined in, like
```scala
@ private val x = 2; val y = x + 1
x: Int = 2
y: Int = 3
@ x
cmd1.sc:1: not found: value x
val res1 = x
^
Compilation Failed
```
This PR changes that, not printing any private thing, like
```scala
@ private val x = 2; val y = x + 1
y: Int = 3
```
> Don't print things marked as private

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/runtime/src/main/scala/ammonite/runtime/tools/IvyThing.scala
- integration/src/test/resources/ammonite/integration/basic/ivyResolveItv1.sc
- integration/src/test/resources/ammonite/integration/basic/ivyResolveItv2.sc
- integration/src/test/resources/ammonite/integration/basic/ivyResolveSnapshot1.sc
- integration/src/test/resources/ammonite/integration/basic/ivyResolveSnapshot2.sc
- integration/src/test/resources/some-dummy-library/build.sbt
- integration/src/test/scala/ammonite/integration/BasicTests.scala
- integration/src/test/scala/ammonite/integration/TestUtils.scala
This makes `IvyThing.resolveArtifact` return a boolean along the list of artifacts, saying whether that list can be cached or not. This is then taken into account before writing things to the cache.
> Ensure we don't keep changing artifacts in ivymap

- amm/interp/src/main/scala/ammonite/interp/AmmonitePlugin.scala
- amm/repl/src/test/scala/ammonite/session/EvaluatorTests.scala
Fixes https://github.com/almond-sh/almond/issues/334.
The "used earlier definitions" mechanism of the class-based wrapper was wrongfully nullifying some references to previous commands, even though some of their types were referenced. Which triggered NPEs in some cases (https://github.com/almond-sh/almond/issues/334).
> Fix issue with class-based wrapper

- amm/repl/src/main/scala/ammonite/repl/ApiImpls.scala
- amm/repl/src/main/scala/ammonite/repl/ReplAPI.scala
- amm/repl/src/test/scala/ammonite/unit/ClipboardTests.scala
One of production booster when working with terminals is the ability to read and write from and to the system clipboard. 
This will be extremely useful to run Scala programs on data brought from selected text. An example is selecting part of Ammonite README file on GitHub:
And counting words in the selected text:
```
val words = clipboard.read.split("\n").flatMap(_.split(" ").map(_.toLowerCase))
val wordCount = (Map.empty[String, Int] /: words) { (count, word) =>
count + (word -> (count.getOrElse(word, 0)+1)) 
}
```
I am open to discuss & change implementation details. I have some doubts:
- I  didn't consider this should be under `FileOps` so I created `ClipboardOps`
- If the idea is welcomed further functionality could be added.
- The code could be more abstract and generic.
- ...
> Clipboard operations: xclip or pbcopy/pbpaste style operations.

- .gitignore
- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/repl/src/main/scala/ammonite/repl/Repl.scala
- amm/repl/src/test/scala/ammonite/TestRepl.scala
- amm/repl/src/test/scala/ammonite/TestUtils.scala
- amm/runtime/src/main/scala/ammonite/runtime/ImportHook.scala
- amm/src/main/scala/ammonite/Main.scala
- build.sc
Rather than having the import hooks hardcoded, this allows to inject them as a `Map[Seq[String], ImportHook]` from the main.
The aim at this is for ammonite's downstreams to have a mean of changing the behaviour of the import hooks. In particular, this should allow mill to inject its own version into the resolution logic, in order to avoid discrepencies of versions between mill and the loaded contrib-module / plugins
> Injecting import hooks

- build.sc
Not technically used anywhere within Ammonite, but I find it extremely useful and use it extensively. Now that `--thin` is a thing, anyone who doesn't want it doesn't need to suffer it anyway
> Add back requests-scala to the classpath

- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
- amm/replApi/src/main/scala/ammonite/repl/api/Frame.scala
- amm/replApi/src/main/scala/ammonite/repl/api/ReplClassLoader.scala
- amm/runtime/src/main/scala/ammonite/runtime/ClassLoaders.scala
- build.sc
- integration/src/test/resources/some-dummy-library/project/build.properties
- integration/src/test/scala/ammonite/integration/BasicTests.scala
- integration/src/test/scala/ammonite/integration/ProjectTests.scala
- integration/src/test/scala/ammonite/integration/TestUtils.scala
This PR gives a more precise type to `ammonite.repl.api.Frame.classLoader`. This gives access via the api to the in-memory byte code of the repl-defined classes, that `SpecialClassLoader` has.
I'm using that from [ammonite-spark](https://github.com/alexarchambault/ammonite-spark) in particular, to pass the repl-defined classes to spark.
This is somehow a substitute to the [`-Yrepl-outdir`](https://github.com/apache/spark/blob/5264164a67df498b73facae207eda12ee133be7d/repl/src/main/scala/org/apache/spark/repl/Main.scala#L70) option of the default scala repl. Except that we directly access the byte code in memory here, rather than on disk. And no option has to be passed beforehand for that to work.
> Allow to access byte code of in-memory classes via the api

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
These changes should be inocuous, yet add back _some_ source compatibility with Ammonite 1.6.7 (allows downstream users to keep supporting 2.11 via 1.6.7, while still depending on the latest Ammonite for 2.12 and 2.13).
> Tweak interpreter constructor

- build.sc
Both had module name [`ammonite-api`](https://repo1.maven.org/maven2/com/lihaoyi/ammonite-api_2.13.0/) before that. This changes this to `ammonite-interp-api` and `ammonite-repl-api`.
> Fix interp-api and repl-api module names

- amm/interp/api/src/main/scala/ammonite/interp/api/InterpAPI.scala
- amm/interp/api/src/main/scala/ammonite/interp/api/IvyConstructor.scala
- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/interp/src/main/scala/ammonite/interp/IvyThing.scala
- amm/interp/src/main/scala/ammonite/interp/Pressy.scala
- amm/repl/src/main/scala/ammonite/main/Defaults.scala
- amm/repl/src/main/scala/ammonite/repl/Repl.scala
- amm/repl/src/test/scala/ammonite/session/ProjectTests.scala
- amm/runtime/src/main/scala/ammonite/runtime/ImportHook.scala
- amm/runtime/src/main/scala/ammonite/runtime/Storage.scala
- amm/src/main/scala/ammonite/Main.scala
- amm/src/test/resources/scripts/Resolvers.sc
- amm/src/test/resources/scripts/ResolversFail.sc
- amm/src/test/resources/scripts/loadIvyAdvanced.sc
- build.sc
This PR replaces `io.get-coursier::coursier` by `io.get-coursier:interface` (living [there](https://github.com/coursier/interface)), which provides a stripped down coursier API and has no dependency (thanks to shading / proguarding).
This allows to remove the dependencies towards:
- shapeless,
- argonaut,
- argonaut-shapeless,
- scala-xml (only when `--thin` is passed for that one).
This changes a little bit how custom dependencies can be loaded with written-down `coursier.Dependency`, like
```
@ interp.load.ivy(coursierapi.Dependency.of("org", "name", "ver").withClassifier("classifier"))
```
instead of
```
@ import coursier._
@ interp.load.ivy(dep"org:name:ver".copy(attributes = Attributes(classifier = Classifier("classifier"))))
```
> Only use coursier via coursier-interface 

- amm/interp/src/main/scala/ammonite/interp/IvyThing.scala
- amm/repl/src/test/scala/ammonite/session/ProjectTests.scala
- amm/src/main/scala/ammonite/Main.scala
- build.sc
This PR adds tests illustrating how:
- not to fetch source JARs (https://github.com/lihaoyi/Ammonite/issues/763#issuecomment-495812048)
- fetch artifacts with fancy types (`so` - https://github.com/lihaoyi/Ammonite/issues/988, …)
Both rely on "resolution hooks" (`interp.resolutionHooks += { fetch => /* customize coursierapi.Fetch instance */ }`), added some time ago.
This required a small fix to work well (ensuring we don't check from and write results to the ivy cache if some resolution hooks were added, as the possible tweaks from resolution hooks aren't reflected in the ivy cache key - and I'm not sure adding them to the cache key is worth the hassle…).
> Tweak ivy cache

- build.sc
It depends on interp-api, that is fully cross-versioned, so it should be fully cross-versioned itself too.
Without this, `com.lihaoy:ammonite-runtime_2.12` depends on `com.lihaoyi:ammonite-repl-api_2.12.9`, which makes `com.lihaoyi:ammonite_2.12.8` pulls both `com.lihaoy:ammonite-repl-api_2.12.8` and `com.lihaoy:ammonite-repl-api_2.12.9`.
> Full cross scala version for runtime

- build.sc
Improve cross scala releases support within ammonite for libraries relying on `org.scala-lang.modules::scala-collection-compat` which bring back some scala 2.13 scala collection feature to scala release 2.11 and 2.12.
> Update scala-collection-compat to fix jdk.CollectionConverters issue

- build.sc
- ops/src/test/scala/test/ammonite/ops/OpTests.scala
This brings in the new standardization on [geny.Writable](https://github.com/lihaoyi/geny#writable), allowing much more seamless interop between the various libraries
> Bump os-lib, upickle, requests versions

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/interp/src/main/scala/ammonite/interp/IvyThing.scala
- amm/runtime/src/main/scala/ammonite/runtime/ImportHook.scala
- amm/runtime/src/main/scala/ammonite/runtime/Storage.scala
- build.sc
This bumps the coursier-interface version. An extra commit also makes sure we preserve the order of the JARs returned by coursier, now that coursier returns them in a deterministic order by default.
> Bump coursier

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
There's no point in hashing `classPathWhilelist` there, as it's not used during resolution.
> Remove unnecessary element in cache key

- amm/interp/src/main/scala/ammonite/interp/CompilerLifecycleManager.scala
`Classpath.classpath(headFrame.classloader, …)` should already contain `headFrame.classpath`, it seems there's no need to add it again.
> Remove duplicate classpath entries

- amm/interp/src/main/scala/ammonite/interp/Compiler.scala
It seems this has to be done manually. My upcoming BSP support PR will have a test for that (via the semanticdb plugin).
> Pass their settings to compiler plugins

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/interp/src/main/scala/ammonite/interp/PredefInitialization.scala
- amm/src/test/scala/ammonite/interp/CachingTests.scala
This saves a few "Compiling…" steps when starting Ammonite with an empty cache.
> Don't go through compiler to add bridge imports

- .travis.yml
- build.sc
The changes here import the PGP secret key the same way as [sbt-ci-release](https://github.com/olafurpg/sbt-ci-release).
@lihaoyi You should just have to add a Travis env var named `SONATYPE_PGP_SECRET`, whose value can be copied with
```bash
gpg --armor --export-secret-keys $LONG_ID | base64 | pbcopy
gpg --armor --export-secret-keys $LONG_ID | base64 -w0 | xclip
```
for this to work. `LONG_ID` can be found in the output of `gpg --list-keys`
```bash
$ gpg --list-keys
…
pub   rsa2048 2020-01-29 [SC] [expire : 2022-01-28]
8011FD49DC1749CD64137AF3CD1B9D8DC84ECA56
uid          [  ultime ] Alexandre Archambault (Travis CI coursier) <alexandre.archambault+traviscicoursier@gmail.com>
sub   rsa2048 2020-01-29 [E] [expire : 2022-01-28]
…
```
(in this example it's …
> Import pgp key like sbt-ci-release does

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/src/main/scala/ammonite/Main.scala
- mill
This will allow us to do things like `interp.watchValue(os.list(...))` to re-run a script if the shallow listing of files changes, without caring about the deep hash of everything in the directory tree. 
This will be useful for e.g. Mill cross modules, where we only need to re-run the script when the shallow listing changes while "deep" changes are handled by Mill itself
> Add ability to watch arbitrary expressions in scripts

- amm/interp/src/main/scala/ammonite/interp/script/ScriptCompiler.scala
- amm/interp/src/main/scala/ammonite/interp/script/SemanticdbProcessor.scala
These can happen if when the BSP client is reading some of the files in the target directory, and we want to clean it up prior to writing new files in it. Those files should be overwritten later on anyway, or removed in a later successful clean-up.
I think this is what's happening [here](https://github.com/scalameta/metals/pull/1538/checks?check_run_id=599722489#step:6:4191).
> Ignore DirectoryNotEmptyException-s in ScriptCompiler

- amm/src/test/resources/scriptLevelCaching/ivyCachedResourceTest.sc
- amm/src/test/resources/scriptLevelCaching/testFileImport.sc
- amm/src/test/scala/ammonite/interp/CachingTests.scala
Seems the return type of some `Scripts.runScript` calls weren't checked in `CachingTests`. Checking them showed that two tests weren't actually run. This PR fixes that.
(This test ended up actually failing, in developments of mine I didn't push yet…)
> Fix caching tests

- amm/interp/src/main/scala/ammonite/interp/CompilerLifecycleManager.scala
- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/repl/src/main/scala/ammonite/main/Defaults.scala
- amm/repl/src/main/scala/ammonite/repl/Repl.scala
- amm/repl/src/test/scala/ammonite/TestRepl.scala
- amm/repl/src/test/scala/ammonite/TestUtils.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
- amm/runtime/src/main/scala/ammonite/runtime/Storage.scala
- amm/src/main/scala/ammonite/Main.scala
- amm/src/test/scala/ammonite/interp/CachingTests.scala
- amm/src/test/scala/ammonite/session/ScriptTests.scala
- amm/util/src/main/scala/ammonite/util/Imports.scala
This PR replaces the hardcoded predef scripts (like [these](https://github.com/lihaoyi/Ammonite/blob/6e2245ec489eef51e7971e89205aa3dc8d1dbbfa/amm/repl/src/main/scala/ammonite/main/Defaults.scala#L28-L53) or [this one](https://github.com/lihaoyi/Ammonite/blob/d8b22aa47bcc0f26f8d435f73c8e98b401621932/amm/src/main/scala/ammonite/Main.scala#L358-L361)), by hardcoded `ImportData`. This is made possible by the hardcoded predef scripts consisting only of imports.
This allows to scrap the frequent upfront predef compilations, like
```
Compiling (synthetic)/ammonite/predef/DefaultPredef.sc
```
(which happen when starting a new Ammonite version, or when starting Ammonite for the first time in a given directory)
> Inline hard-coded predef imports

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/repl/src/main/scala/ammonite/main/Defaults.scala
- amm/repl/src/main/scala/ammonite/repl/Repl.scala
- amm/repl/src/test/scala/ammonite/TestRepl.scala
- amm/repl/src/test/scala/ammonite/TestUtils.scala
- amm/src/main/scala/ammonite/Main.scala
- amm/src/test/scala/ammonite/interp/CachingTests.scala
- amm/src/test/scala/ammonite/session/ScriptTests.scala
This mainly merges `Default.predefImports` and `Main.extraPredefImports`. They were used together almost all the time. Except in some tests, where `Default.predefImports` was used alone, but adding `extraPredefImports` isn't a problem.
This also moves them to `Interpreter`, where they make a sensible default for `Interpreter.initializePredef` (and the BSP support will be able to re-use them from there).
> Tweak predef imports

- amm/repl/src/main/scala/ammonite/repl/AmmoniteFrontEnd.scala
- amm/repl/src/main/scala/ammonite/repl/Repl.scala
- amm/repl/src/main/scala/ammonite/repl/Signaller.scala
- terminal/src/main/scala/ammonite/terminal/Terminal.scala
- terminal/src/main/scala/ammonite/terminal/Utils.scala
This closes issue #729.
There are several issues with the interaction between the terminal, SIGINT, and signal handling:
* `Signaller` actually does not restore the previous signal handler in its finally block; it reinstalls the current handler (unless someone modifies `Signaller.handlers` directly). This seems to be simply a bug.
* Users cannot send SIGINT to Ammonite while the input line is being read in, including during auto completion. Instead, Ammonite interprets the control character literally. However, this behavior is still in place during autocompletion, so users cannot Ctrl-C to cancel autocompletion, as this doesn't send SIGINT.
* Even if users could send SIGINT to Ammonite when typing, the Signaller is only invoked after having read in the users' input.
This PR addresses all …
> Handle SIGINT When Reading User Input

- readme/Repl.scalatex
The documentation refers to `run-main`, but this should be `runMain`
> Fix sbt instructions

- amm/interp/src/main/scala/ammonite/interp/Parsers.scala
- amm/interp/src/main/scala/ammonite/interp/Preprocessor.scala
- amm/interp/src/main/scala/ammonite/interp/script/AmmoniteBuildServer.scala
- amm/interp/src/main/scala/ammonite/interp/script/Script.scala
- amm/interp/src/main/scala/ammonite/interp/script/ScriptCache.scala
- amm/interp/src/main/scala/ammonite/interp/script/ScriptProcessor.scala
- amm/interp/src/main/scala/ammonite/interp/script/SingleScriptCompiler.scala
- amm/repl/src/main/scala/ammonite/repl/AmmoniteFrontEnd.scala
- amm/src/test/resources/bsp/error/error-and-invalid-import-file.sc
- amm/src/test/resources/bsp/error/invalid-import-file.sc
- amm/src/test/scala/ammonite/interp/script/AmmoniteBuildServerTests.scala
This allows to get red squiggles under `import $file`s when the corresponding fie is not found, when editing Ammonite scripts in metals.
> Report wrong import $file-s via diagnostics in BSP

- amm/repl/src/test/scala/ammonite/TestUtils.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
- amm/repl/src/test/scala/ammonite/session/EvaluatorTests.scala
- amm/repl/src/test/scala/ammonite/session/ProjectTests.scala
- amm/src/test/scala/ammonite/session/ScriptTests.scala
- build.sc
That's needed for Scala 3 support in particular, as pprint is published for Scala 3 only for `0.6.0` onwards.
> Update PPrint to 0.6.0

- build.sc
Only version also published for Scala `3.0.0-M2`.
> Update scala-collection-compat to 2.3.1

- readme/Ops.scalatex
- readme/Repl.scalatex
Ammonite works fine on Windows.  
Even if it doesn't, we should encourage users at least to try it! :)
Maybe we should also mention https://get-coursier.io/docs/cli-installation ?  
With `cs setup` you get all the necessary tools for working with scala, including Ammonite.
> Show instructions per OS.

- .github/workflows/actions.yml
- build.sc
This is my attempt to finish the Scala 2.13.5 bump and also properly test it. See #1159 
I switched to a test matrix, to make it more obvious where to add/change the scala version in case of a bump. IMHO, we should add _all_ scala versions, to which we have a release for, to the test matrix.
> Use latest Scala 2.13 for build and use a test matrix in CI

- amm/interp/api/src/main/scala/ammonite/interp/api/InterpAPI.scala
- amm/repl/api/src/main/scala/ammonite/repl/api/ReplAPI.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
- amm/repl/src/test/scala/ammonite/session/ProjectTests.scala
- readme/Repl.scalatex
These are mostly cosmetic changes for easier reading.  
Some examples didn't even work on scala 2.12/2.13 so I updated them.
Closes #1158 
An aside:  
Should we drop everything referencing scala 2.11 ?  
Because Ammonite is released only for 2.12+ AFAIK.  
There are refs in tests, docs etc...
> Fix REPL docs

- amm/src/test/resources/mains/Args.sc
- amm/src/test/resources/mains/Args2.sc
- integration/src/test/resources/ammonite/integration/basic/HttpApi.sc
- readme/Scripts.scalatex
Fixes:
- replaced `Ivy artifacts` with `Ivy/Maven artifacts`, just so users don't get confused whether they can use Maven repos...
- removed `scopt` refs
- removed `predefShared`
> Fix Scripts docs

- build.sc
1.3.14/13.15 are binary incompatible with previous versions, so I bumped the middle number. Better to make Ammonite depend on the new version and then bump it's number as well
> Bump uPickle to 1.4.0

- amm/compiler/src/main/scala-3/ammonite/compiler/Preprocessor.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
Rather than as lazy values, or by crashing
> Pretty-print given-s in Scala 3 as such

- build.sc
This value has been working fine on some of my personal biggest mill projects (coursier, almond). Right now, the mill release jobs fail almost all the time on master.
> Increase release timeouts to 10 minutes

- readme/Sample.scala
- readme/Shell.scalatex
There were some bugs in `Sample.scala` which were truncating the script results, adding `$ bash` to every line of bash output and a typo (wrong directory name) in `Shell.scalatex` which caused a bash command to fail. These errors have made it challenging for those learning Ammonite via the documentation at https://ammonite.io/, as numerous inline examples were missing (not rendered).
This PR addresses the rendering problems for `@compare` and `ammSample`, which were reported in the following issues:
Fixes: https://github.com/com-lihaoyi/Ammonite/issues/1203, fixes: https://github.com/com-lihaoyi/Ammonite/issues/1102, fixes: https://github.com/com-lihaoyi/Ammonite/issues/1086, fixes: https://github.com/com-lihaoyi/Ammonite/issues/1132.
I am new to Ammonite and found it difficult to follow …
> Fix documentation rendering (`@compare`,` ammSample` bugs)

- amm/repl/src/main/scala/ammonite/repl/ApiImpls.scala
- amm/repl/src/main/scala/ammonite/repl/PPrints.scala
Fixes #1206, in particular the call for `ls!` will now use the Repl's frontEnd width.
> The pretty-printer  uses Repl width directly

- build.sc
It's compiled only in Scala 2, and used via dotty compat in Scala 3. For Scala 2, it depends on Scala 2 pprint. For Scala 3, it depends on Scala 3 pprint.
Without these changes, only the latter module ends up being published, which makes ammonite for 2.13.6 pull pprint for Scala 3 (along with pprint for Scala 2), which is a problem.
Also, the same module (`com.lihaoyi:ammonite-compiler-interface_2.13.6`) was built and published twice. A few commits ago, these were published in the same batch, so only one (apparently the latter) ended up actually published. Since two commits on master, these are published in separate batches, which makes one of them fail (because it tries to publish a module already published by the other batch).
With the changes here, we now publish …
> Disambiguate compiler-interface module name

- .github/workflows/actions.yml
- build.sc
Requires https://github.com/scalameta/scalameta/pull/2474.
> Update Scala to 2.12.15

- amm/src/main/scala/ammonite/Main.scala
- amm/src/main/scala/ammonite/main/TrapExitSecurityManager.scala
When user runs the script with `--watch` option and if the script calls `sys.exit`, ammonite exits and doesn't stay in the watch loop. 
This PR adds a `TrapExitSecurityManager` that would be used when the `--watch` option is activated. When there is a `sys.exit` in the scrips, the special `TrapExitException` will be thrown giving a helpful output for the user:
Please let me know what you think 🙂
> Issue #1148 trap exit when running script with --watch option

- build.sc
- Bump requests to `0.6.9` (first version released for Scala 3)
> Use Scala 3 dependencies for upickle and requests

- amm/compiler/src/main/scala-2/ammonite/compiler/Compiler.scala
- amm/compiler/src/main/scala-3/ammonite/compiler/Compiler.scala
- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
- amm/repl/src/test/scala/ammonite/session/FailureTests.scala
- amm/src/test/resources/lineNumbers/sourceCodeMetadata.sc
- amm/src/test/scala/ammonite/interp/YRangeposTests.scala
- amm/src/test/scala/ammonite/main/InProcessMainMethodRunner.scala
- amm/src/test/scala/ammonite/main/LineNumberTests.scala
- amm/src/test/scala/ammonite/main/MainTests.scala
- build.sc
Fixes https://github.com/com-lihaoyi/Ammonite/issues/646
Fixes https://github.com/com-lihaoyi/Ammonite/issues/493
Previously we constructed a `new io.VirtualFile` with an identical name and path, both short, to ensure stack traces included only the file name. The correct thing to do is to provide separate names and paths, so stack traces can use the file name while compiler errors can use the full file path. This is done differently in Scala2 and Scala3 due to differences in the compiler APIs, but the end result is the same
This makes the parse/compile errors line up more with how the normal Scala compiler reports them, and fixes `sourcecode.File` to properly report the full path of the script file.
Updated the existing LineNumberTests to verify the fixed behavior, and added a new …
> Use full file path for parse error messages and compiler metadata

- .github/workflows/actions.yml
- build.sc
Also updated acyclic to 0.3.1 and scalameta to 4.4.32 for Scala 2.13.8 support.
> Update Scala version to 2.13.8

- amm/src/main/scala/ammonite/AmmoniteMain.scala
- amm/src/main/scala/ammonite/Main.scala
- amm/src/main/scala/ammonite/MainRunner.scala
This avoids breaking when tools and scripts designed with Ammonite 2.4 and earlier try to start Ammonite.
> Re-added but deprecated old Main entry point

- build.sc
Instead of publishing Scala 2 modules used by Scala 3 Ammonite with `ammonite-cross-23-`, like `ammonite-cross-23-interp-api_2.13.7`, this puts the target Scala 3 version in the prefix, like `ammonite-cross-3.1.0-interp-api_2.13.7`. That way, the modules originating from Scala `3.0.2` and `3.1.0` say, can't clash during the release stages of Ammonite.
> Disambiguate cross Scala 2 / 3 artifact names more

- amm/compiler/src/main/scala-3/ammonite/compiler/Compiler.scala
- amm/interp/src/main/scala/ammonite/interp/script/AmmoniteBuildServer.scala
- amm/interp/src/main/scala/ammonite/interp/script/Diagnostic.scala
- amm/interp/src/main/scala/ammonite/interp/script/ScriptProcessor.scala
- amm/interp/src/main/scala/ammonite/interp/script/SingleScriptCompiler.scala
- amm/src/test/scala/ammonite/main/LineNumberTests.scala
- amm/util/src/main/scala/ammonite/util/Position.scala
- amm/util/src/main/scala/ammonite/util/PositionOffsetConversion.scala
- build.sc
- integration/src/test/scala/ammonite/integration/ErrorTruncationTests.scala
- integration/src/test/scala/ammonite/integration/LineNumberTests.scala
I didn't take the time to update positions in diagnostics returned by dotty, when adding Scala 3 support, so positions were stripped in Scala 3 diagnostics. This PR fixes that.
Before:
```text
|  n azzd 3
|  ^^^^^^
|value azzd is not a member of Int, but could be made available as an extension method.
|
|The following import might make progress towards fixing the problem:
|
|  import sourcecode.Text.generate
|
Compilation Failed
```
After:
```text
-- [E008] Not Found Error: cmd0.sc:3:4 -----------------------------------------
3 |  n azzd 3
|  ^^^^^^
|value azzd is not a member of Int, but could be made available as an extension method.
|
|The following import might make progress towards fixing the problem:
|
|  import sourcecode.Text.generate
|
Compilation Failed
```
> Add back positions in Scala 3 diagnostics

- readme/Repl.scalatex
- readme/Scripts.scalatex
Was figuring out a local issue and noticed that this suggests the main Linux install is scala 2.12 when in fact it's a 2.13.
2.12 is referred to in the older scala versions section,
> Linux curl is scala 2.13

- amm/interp/src/main/scala/ammonite/interp/script/AmmoniteBuildServer.scala
- amm/interp/src/main/scala/ammonite/interp/script/ScriptCompiler.scala
- amm/src/test/scala/ammonite/interp/script/AmmoniteBuildServerTests.scala
Previously, we would use the Scala version from the Scala library, which will be 2.13.8 even for Scala 3. Now we take the same version as the compiler.
> bugfix: Set proper Scala version in ScalaBuildTarget data

- build.sc
scala-compiler 2.12.x depends on scala-xml 1.x (rather then 2.x). As a
consequence, most tools kept using scala-xml 1.x, at least in Scala 2.12
(sbt, coursier, ...). This does the same for Ammonite.
Almond was pulling scala-xml 2.x because of that, while still depending
on JARs built against scala-xml 1.x (scala-compiler, coursier). Even
though I didn't run into binary incompatibilities because of that (yet),
this should make things safer in 2.12.
> Keep using scala-xml 1.x in scala 2.12

- amm/compiler/src/main/scala-3/ammonite/compiler/Preprocessor.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
fix: https://github.com/com-lihaoyi/Ammonite/issues/1281
Previously, ammonite REPL couldn't define extension methods
because of the lack of Preprocessor for extension method definition.
```
❯ scala-cli repl --scala 3.1.3 --ammonite
Loading...
Welcome to the Ammonite Repl 2.5.4-11-4f5bf2aa (Scala 3.1.3 Java 17.0.3)
@ extension (foo: Int)
def bar = foo
-- [E006] Not Found Error: cmd0.sc:1:11 ----------------------------------------
1 |val res0 = extension (foo: Int)
|           ^^^^^^^^^
|           Not found: extension
|
| longer explanation available when compiling with `-explain`
-- [E006] Not Found Error: cmd0.sc:1:22 ----------------------------------------
1 |val res0 = extension (foo: Int)
|                      ^^^
|                      Not found: foo
|
| longer explanation …
```
> [Scala3] support extension methods

- readme.md
The previous version of developer documents around
automated testings are written in 6-7 years ago
when the sbt was used for build tools.
https://github.com/com-lihaoyi/Ammonite/commit/ea5227c45f9cb4e8a98071ab42d90450b093e4fc
This commit update the command for automated testing
for mill.
> docs: Update readme about automated testing

- amm/compiler/src/main/scala-2/ammonite/compiler/tools/SourceRuntime.scala
- amm/compiler/src/main/scala-2/ammonite/compiler/tools/source.scala
- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/repl/api/src/main/scala/ammonite/runtime/tools/Tools.scala
fix https://github.com/com-lihaoyi/Ammonite/issues/1254
This PR enables Ammonite-REPL to use `browse` and `source` built-in utilities out of the box.
- `browse`
- As @ches mentioned in https://github.com/com-lihaoyi/Ammonite/issues/1254, `browse` takes implicit `pprint.PPrinter` that is not in the REPL scope by default.
- fixed by giving a default argument https://github.com/com-lihaoyi/Ammonite/commit/05e295855b79a2cd3e861a5b7c81553caa30678a
- `source`
- define `browseSourceCommand` that is called from macro (looks like forgotten to port in https://github.com/com-lihaoyi/Ammonite/commit/ba57f10ab8ca1c5b8c1e2041c9c338d44d1cb885)
- Added `repl.codeColorsImplicit` to `predefImport`, (is this ok?)
- Add `pprint.PPrinter` as default parameters (in a wired way)
- default argument doesn't work …
> Fix source and browse utilities to be able to use out of the box

- amm/compiler/src/main/scala-2/ammonite/compiler/Pressy.scala
- amm/repl/src/test/scala/ammonite/interp/AutocompleteTests.scala
Hi, this PR is a (partial, and Scala 2 only - there appears to be other issues with completions for Scala 3?) fix for https://github.com/com-lihaoyi/Ammonite/issues/965:
https://user-images.githubusercontent.com/17688577/188308492-22450d23-2e45-4c18-9337-dcc2244d5995.mp4
Essentially, if it turns out there are no completion candidates for a snippet, and the the snippet starts with 
```
$ivy.`
```
We just retry by appending a backtick if the string only contains only one backtick... more of a workaround than an in depth fix  described in https://github.com/com-lihaoyi/Ammonite/issues/965#issuecomment-495857542 (there are many valid cases this wouldn't touch), but I hope it would cover the most common ways people would use `import $ivy`, the case described in the issue for example.
Let me …
> Autocomplete (some) ivy Imports when there is no Closing Backtick

- build.sc
@lolgab As part of my review for #1301, here is my attempt to make the workaround setup more readable.
> Make Scala 2 macro workaround more readable (code-wise)

- build.sc
Fixes #1241
Having a sane classpath using the Scala 2.13 compiler to compile a Scala 3 project is _hard_.
This uses some tricks to compile using Scala 2.13 dependencies (since we need the Scala 2.13 macros) and then change the artifacts with Scala 3 artifacts so the Ammonite runtime can compile the macros using the Scala 3 compiler.
> Fix issues with `_3` and `_2.13` dependencies

- amm/src/main/scala/ammonite/main/Scripts.scala
- amm/src/test/scala/ammonite/main/MainTests.scala
mainargs 0.2.3 added support for scala3 :tada:
https://github.com/com-lihaoyi/mainargs/pull/18
The first attempt to upgrade and enable mainargs was https://github.com/com-lihaoyi/Ammonite/pull/1298, but the build changes were better handled by https://github.com/com-lihaoyi/Ammonite/pull/1301
So the only thing left is reenabling mainargs for Scala 3.
> add @main entrypoint support for Scala 3

- build.sc
scala-collection-compat suffers from the same issue seen in the other deps
In sbt we see:
```
Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/..../"), "core"):
[error]    org.scala-lang.modules:scala-collection-compat _3, _2.13
```
> Use_3 for scala-collection-compat

- build.sc
- integration/src/test/scala/ammonite/integration/BasicTests.scala
- integration/src/test/scala/ammonite/integration/ErrorTruncationTests.scala
- integration/src/test/scala/ammonite/integration/LineNumberTests.scala
- integration/src/test/scala/ammonite/integration/ProjectTests.scala
This is a binary incompatible change! The next release version after merge is probably `3.0.0`.
I dropped support for Scala 3.0.x due to the fact, that upickle_3 3.0.0-M2 is build against Scala 3.1.
Ammonite depends also on geny but never made that dependency explicit. I changed that and added a direct dependency where appropriate. With the bump of upickle, we implicitly also bump geny from 0.7.0 to 1.0.0. As a consequence, I also had to update os-lib from 0.8.0 to 0.9.0 as it is also depending on geny, and only version 0.9.0 is compatible to geny 1.0.0.
> Update upickle to 3.0.0-M2

- amm/util/src/main/java/io/github/retronym/java9rtexport/Export.java
`Export.rtTo` needs to be `synchronized` because java.nio.file.Files.copy isn't thread safe: 
https://stackoverflow.com/questions/69796396/is-files-copy-a-thread-safe-function-in-java
and our own handling of `if !exists, then copy` isn't either...
This is very much a concurrency edge case, albeit one that we regularly run into. Without this change, we regularly run into the below when running tests in parallel.
```
java.nio.file.FileAlreadyExistsException: /home/runner/.ammonite/rt-17.0.5.jar
at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:573)
at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:257)
at java.base/java.nio.file.Files.copy(Files.java:1305)
at io.github.retronym.java9rtexport.Export.rtTo(Export.java:88)
at …
```
> fix amm-util java.rt.export race condition: synchronize

- amm/compiler/interface/src/main/scala/ammonite/compiler/iface/CompilerLifecycleManager.scala
- amm/compiler/src/main/scala-2/ammonite/compiler/Compiler.scala
- amm/compiler/src/main/scala-2/ammonite/compiler/CompilerBuilder.scala
- amm/compiler/src/main/scala-2/ammonite/compiler/CompilerExtensions.scala
- amm/compiler/src/main/scala-2/ammonite/compiler/CompilerLifecycleManager.scala
- amm/compiler/src/main/scala-3/ammonite/compiler/Compiler.scala
- amm/compiler/src/main/scala-3/ammonite/compiler/CompilerBuilder.scala
- amm/compiler/src/main/scala-3/ammonite/compiler/CompilerExtensions.scala
- amm/compiler/src/main/scala-3/ammonite/compiler/CompilerLifecycleManager.scala
- amm/repl/src/test/scala/ammonite/DualTestRepl.scala
- amm/repl/src/test/scala/ammonite/TestRepl.scala
- amm/repl/src/test/scala/ammonite/TestUtils.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
- amm/src/main/scala/ammonite/AmmoniteMain.scala
- amm/src/main/scala/ammonite/Main.scala
- amm/src/main/scala/ammonite/MainRunner.scala
- amm/src/main/scala/ammonite/main/Config.scala
- amm/src/test/scala/ammonite/interp/script/AmmoniteBuildServerTests.scala
This adds an `--output-directory` option equivalent to `-Yrepl-outdir` in the default Scala REPL. The latter is [used by the Spark REPL](https://github.com/apache/spark/blob/156a12ec0abba8362658a58e00179a0b80f663f2/repl/src/main/scala-2.12/org/apache/spark/repl/Main.scala#L70) in particular, and I'm planning to use that new option in Spark-related developments (in [ammonite-spark](https://github.com/alexarchambault/ammonite-spark), itself used by [Almond](https://github.com/almond-sh/almond)).
This option basically writes in the passed directory the byte code generated by compiling the user code.
> Allow to write REPL byte code to a directory

- amm/compiler/src/main/scala-2/ammonite/compiler/Compiler.scala
- amm/src/main/scala/ammonite/Main.scala
- build.sc
- integration/src/test/scala/ammonite/integration/BasicTests.scala
- integration/src/test/scala/ammonite/integration/TestUtils.scala
This is a problem when launching Ammonite with a manual `java -cp` command, and adding JARs alongside it. If some of those JARs don't exist, Ammonite currently crashes (fails to compile anything with a stacktrace, or prints a stacktrace and exit if there's a predef). This PR fixes that.
> Be fine with non-existent files in class path in Scala 2

- readme/Footer.scalatex
So, I noticed that the documentation contains a strange phrase, saying that the latest version of Scala is 2.12.
This is a few versions out of date! I've fixed it here.
However I think it's also worth you taking a look at the older versions listed, as currently it's just showing up a 2.12 version, and I think you have a 2.13 version around too?
> doc: Fix incorrect mention of Scala 2.12 being latest

- amm/repl/src/test/scala/ammonite/DualTestRepl.scala
- amm/repl/src/test/scala/ammonite/session/BuiltinTests.scala
- amm/runtime/src/main/scala/ammonite/runtime/ImportHook.scala
- build.sc
- readme/Repl.scalatex
See the added documentation. This makes the following work, while not breaking today's `import $cp` syntax:
```scala
@ import $cp.`/foo/a/b.jar`
@ import $cp.`/foo/a/b.jar;/foo/a/c.jar;/foo/a/d.jar`
@ import $cp.`/foo/a/*`
@ import $cp.`../foo/a/*`
@ import $cp.`${the.foo.dir}/a/*`
```
That syntax makes it easier to add elements to the class path using `import $cp`, when one gets these paths via another tool: one doesn't have to convert it to `import $cp.^.^.^.foo.a.b`. And it also:
- substitutes Java properties
- accepts multiple elements separated by `;` (Linux / macOS) or `:` (Windows)
- accepts some blobs to add all JARs in a directory
This relies on [a library](https://github.com/coursier/class-path-util) recently added in then spin off from coursier. The `--extra-jar` option of `cs …
> Accept files paths and more refined class paths in 'import $cp'

- LICENSE
I also changed the copyright year from 2014 to 2015. This is because the year in copyright notice refers to the year of first publication as italicised here: https://opensource.stackexchange.com/questions/6389/how-do-the-years-specified-in-a-copyright-statement-work . According to the GitHub API this repository was not created until 2015: https://api.github.com/repos/com-lihaoyi/Ammonite :octocat:
> Highlight MIT in LICENSE

- amm/compiler/src/main/scala-2/ammonite/compiler/Parsers.scala
- amm/repl/src/test/scala/ammonite/session/FailureTests.scala
The current Parser ignores whitespaces at the beginning of the code block, which may result in incorrect line number in an exception stackTrace:
```
@ {
1 / 0
} 
java.lang.ArithmeticException: / by zero
ammonite.$sess.cmd0$.<init>(cmd0.sc:1)
ammonite.$sess.cmd0$.<clinit>(cmd0.sc)
```
This PR changes it so the result will be
```
@ { 
1 / 0
} 
java.lang.ArithmeticException: / by zero
ammonite.$sess.cmd0$.<init>(cmd0.sc:4)
ammonite.$sess.cmd0$.<clinit>(cmd0.sc)
```
(line number is 4 instead of 1)
This it done by introducing a new parser which does not ignore leading whitespaces
Please note that it changes this only for Scala 2. Scala 3 impl has a different parsing logics which I didn't have time to dive into yet
New tests in `FailureTests` checking line numbers
> Fix line numbers in exceptions for multi-line code blocks

- amm/compiler/src/main/scala-2/ammonite/compiler/DefaultPreprocessor.scala
- amm/compiler/src/main/scala-2/ammonite/compiler/Parsers.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
This fixes a recent regression when a comment precedes an import in a code block, like
```
@ {
// hello
import cats.kernel._
}
```
(introduced in https://github.com/com-lihaoyi/Ammonite/pull/1361, that fixes nice things otherwise)
Before this PR, ones gets:
```text
Welcome to the Ammonite Repl 3.0.0-M0-33-94c5ce87 (Scala 2.13.11 Java 1.8.0_362)
@ import $ivy.`org.typelevel::cats-kernel:2.6.1`
import $ivy.$
@ {
// hello
import cats.kernel._
}
import hello
import cats.kernel._
```
(note the `import hello` towards the end)
With this PR, we get the expected output at the end:
```text
Welcome to the Ammonite Repl 3.0.0-M0-35-3a5444f1 (Scala 2.13.11 Java 1.8.0_362)
@ import $ivy.`org.typelevel::cats-kernel:2.6.1`
import $ivy.$
@ {
// hello
import cats.kernel._
}
import cats.kernel._
```
> Fix recent regression with comments right before imports

- amm/runtime/src/main/scala/ammonite/runtime/ImportHook.scala
- build.sc
It lives in [this repository](https://github.com/coursier/dependency). Scala CLI uses that parser too. It allows to add support for things like 'org:name:ver,intransitive' for example
> Use coursier-dependency to parse dependencies

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
- amm/repl/src/test/scala/ammonite/DualTestRepl.scala
- amm/repl/src/test/scala/ammonite/TestRepl.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
- amm/repl/src/test/scala/ammonite/session/FailureTests.scala
This allows users of Ammonite as a library to customize the wrapper name used to wrap code for one more adapted to their context (in [Almond](https://github.com/almond-sh/almond), this allows to use `cell` rather than `cmd` - the former makes more sense in notebooks where Almond is used)
> Factor wrapper name in Interpreter

- amm/interp/src/main/scala/ammonite/interp/Interpreter.scala
This allows users of Ammonite-as-a-library to do things like
```scala
import ammonite.compiler.CompilerExtensions._
interp.interpApi.preConfigureCompiler(???)
```
to add / configure scalac options via the API
> Make Interpreter#interApi public

- amm/compiler/src/main/scala-2/ammonite/compiler/Compiler.scala
- amm/compiler/src/main/scala-3/ammonite/compiler/Compiler.scala
I've been seeing weird `FileAlreadyExistsException`-s with `metadata.json` files, from Almond. With caching of things via `Storage.Folder` involved…
```
java.nio.file.FileAlreadyExistsException: /var/folders/nh/1smqz1yx5c930wqsx6w7crrh0000gn/T/almond-output7192041737362156701/metadata.json
sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
java.nio.file.Files.newByteChannel(Files.java:361)
os.write$.write(ReadWriteOps.scala:64)
os.write$.apply(ReadWriteOps.scala:77)
ammonite.compiler.Compiler$.addToClasspath$$anonfun$2$$anonfun$1(Compiler.scala:519) …
```
> Overwrite things when copying compiler products in directory

- amm/interp/src/main/scala/ammonite/interp/script/AmmoniteBuildServer.scala
- amm/interp/src/main/scala/ammonite/interp/script/DummyBuildServerImplems.scala
- build.sc
bsp4j:2.0.0-M6 depends on com.google.code.gson:gson:2.8.2 that has a known vulnerability:
- https://nvd.nist.gov/vuln/detail/CVE-2022-25647 (High: 7.5 CVSS)
bsp4j:2.1.0-M4 depends on com.google.code.gson:gson:2.9.1 that is not affected by CVE-2022-25647
> bsp4j: 2.0.0-M6 → 2.1.0-M5

- build.sc
Includes:
https://github.com/scalameta/scalameta/pull/3178
CVEs:
https://nvd.nist.gov/vuln/detail/CVE-2022-3510 (High: 7.5 CVSS)
https://nvd.nist.gov/vuln/detail/CVE-2022-3509 (High: 7.5 CVSS)
https://nvd.nist.gov/vuln/detail/CVE-2022-3171 (High: 7.5 CVSS)
> scalameta: 4.7.8 → 4.8.5

- amm/compiler/src/main/scala-2/ammonite/compiler/Parsers.scala
- amm/repl/src/test/scala/ammonite/session/AdvancedTests.scala
This fixes a regression introduced in https://github.com/com-lihaoyi/Ammonite/pull/1361. This makes the following work again as expected:
```scala
@ {
import $ivy.`org.typelevel::cats-kernel:2.6.1`
}
```
Before the changes here, in Scala 2.x, one gets an error like
```text
cmd0.sc:2: object org.typelevel::cats-kernel:2.6.1 is not a member of package ammonite.$ivy
import $ivy.`org.typelevel::cats-kernel:2.6.1`
^
Compilation Failed
```
> Fix recent regression with import hooks in blocks

- amm/src/main/scala/ammonite/Main.scala
Forgot to call `.value` and the result was `.asInstanceOf[TypeName(Int)]` instead of `.asInstanceOf[Int]`
> Call `.value` to get the actual typeName in Main

- build.sc
This fixes the issue https://github.com/com-lihaoyi/Ammonite/issues/1386:
```
> ./mill -i amm.repl[3.2.2].test
GITHUB REF None
fatal: no tag exactly matches 'cdeaa580bf128779686991a838623dd3a75af49b'
[296/296] amm.repl[3.2.2].test
java.lang.ClassNotFoundException: utest.runner.Framework
java.lang.ClassNotFoundException: utest.runner.Framework
at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
at mill.api.ClassLoader$$anon$1.findClass(ClassLoader.scala:47)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
at mill.testrunner.TestRunner$.framework(TestRunner.scala:412)
at mill.testrunner.TestRunner$.$anonfun$main$2(TestRunner.scala:252)
at …
```
> Fix build, remove TestModule.UTest from AmmInternalModule

- build.sc
This unblocks update to Scala 2.12.19
> Update acyclic from 0.3.9 to 0.3.10

- amm/repl/src/test/scala/ammonite/session/BuiltinTests.scala
Official [Compiler Flags](https://ammonite.io/#CompilerFlags) documentation do not mention how to set settings for scala 3 compiler.
Maybe adding a comment like this in 2.12?:
```scala
@ // Disabling default Scala imports
@ List(1, 2, 3) + "lol"
res0: String = "List(1, 2, 3)lol"
@ interp.configureCompiler(_.settings.noimports.value = true)
@ // interp.preConfigureCompiler(ctx => ctx.setSetting(ctx.settings.YnoImports, true)) // Dotty
```
Fixes #1192
> Add scala 3 compiler settings test

- build.sc
We have both `scala-collection-compat_2.13` and `scala-collection-compat_3` in the classpath.
Update `scala-collection-compat` to the same version as the one used by scalameta commons
> Remove `scala-collection-compat_2.13` dependency from Scala 3

- build.sc
We only want to publish for 3.3.x, because it is compatible with all future versions, whereas 3.4.x is not compatible with 3.3.x and causes conflicts when they both have the same `_3` suffix
Fixes https://github.com/com-lihaoyi/Ammonite/issues/1504
> Avoid publishing binCrossScalaVersions cross-built modules for 3.4.2

- amm/repl/src/test/scala/ammonite/session/BuiltinTests.scala
Enable settings tests for any 2.12 versions.
This is a follow up of this conversation https://github.com/com-lihaoyi/Ammonite/pull/1484#pullrequestreview-2044852416 I had previously with @lefou.
Tested with `mill -i -w 'amm.repl[{2.12.19,2.13.14,3.4.2}].test.testOnly' -- 'ammonite.session.BuiltinTests.settings'` so all `2.12`, `2.13` and `3` latest versions are passing.
> Add scala 2.13 compiler settings test

- .github/workflows/actions.yml
- .github/workflows/run-tests.yml
- amm/repl/src/test/scala/ammonite/session/ProjectTests.scala
- build.sc
* We probably only need to each on each Java and Scala version once, rather than on the full cross matrix of all combinations. 
* We probably don't need to test every PR with every single Scala version. For now, for each Scala major version I picked three minor versions: highest, lowest, and one in the middle. 
* Replaced `__.publishLocal` with `__.compile`, which should hopefully catch most of the same bugs but be much cheaper not creating jars
* I suspect the `unitTest` and `integrationTest` helper tasks were not doing the right thing - they were taking far longer than they should have been taking - but I couldn't figure out why. For now I just ditched them and use Mill queries to select the tests I want manually
* Turned on Mill parallelism
* We drop CI for Java 8, in line with the …
> Shrink CI matrix

- .github/workflows/run-tests.yml
- build.sc
https://contributors.scala-lang.org/t/scala-2-13-15-release-planning/6649/10
`Scala 2.13.15` has been released, let's support it.
Depends on
- [] https://github.com/com-lihaoyi/acyclic/pull/138
- [] https://github.com/typelevel/kind-projector/pull/291
> Add support for Scala 2.13.15

- amm/compiler/src/main/scala-3.0.0-3.3.1/dotty/ammonite/compiler/AmmCompletion.scala
- amm/compiler/src/main/scala-3.3.2+/dotty/ammonite/compiler/AmmCompletion.scala
- amm/compiler/src/main/scala-3.4.2+/dotty/ammonite/compiler/AmmCompletion.scala
- amm/compiler/src/main/scala-3.5.0+/dotty/ammonite/compiler/AmmCompletion.scala
Fix #1567
Fix #1538
I'm actually not sure what causes the crash or what this fix does to fix that. The `AmmCompletion.scala` file seemed to be copied from dotty's `interactive/Completions.scala` and adding [this](https://github.com/scala/scala3/blob/8ab7ebefecfd3d7b1e23a47238556c125ed795e8/compiler/src/dotty/tools/dotc/interactive/Completion.scala#L57) fixes the crash.
Tested manually for Scala 3.5.1, 3.4.3, 3.3.4.
> Fix a Scala 3 completion error

- .github/workflows/run-tests.yml
- amm/interp/src/main/scala/ammonite/interp/script/ScriptCompiler.scala
- build.mill
> Add support for Scala 3.5.2

- .github/workflows/run-tests.yml
Seems upcoming Mill versions require JDK >= 11, see the CI failures of https://github.com/com-lihaoyi/Ammonite/pull/1608
> Use JDK 11 in CI jobs that were still on JDK 8
